(function(h,k){function n(a,b,d){if(d===k&&a.nodeType===1)if(name="data-"+b.replace(Za,"$1-$2").toLowerCase(),d=a.getAttribute(name),typeof d==="string"){try{d=d==="true"?!0:d==="false"?!1:d==="null"?null:!c.isNaN(d)?parseFloat(d):$a.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=k;return d}function v(a){for(var b in a)if(b!=="toJSON")return!1;return!0}function t(a,b,d){var e=b+"defer",f=b+"queue",g=b+"mark",j=c.data(a,e,k,!0);j&&(d==="queue"||!c.data(a,f,k,!0))&&(d==="mark"||!c.data(a,g,
k,!0))&&setTimeout(function(){!c.data(a,f,k,!0)&&!c.data(a,g,k,!0)&&(c.removeData(a,e,!0),j.resolve())},0)}function y(){return!1}function F(){return!0}function W(a,b,d){var e=c.extend({},d[0]);e.type=a;e.originalEvent={};e.liveFired=k;c.event.handle.call(b,e);e.isDefaultPrevented()&&d[0].preventDefault()}function G(a){var b,d,e,f,g,j,q,k,m,h,l,n=[];f=[];g=c._data(this,"events");if(!(a.liveFired===this||!g||!g.live||a.target.disabled||a.button&&a.type==="click")){a.namespace&&(l=RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+
"(\\.|$)"));a.liveFired=this;var s=g.live.slice(0);for(q=0;q<s.length;q++)g=s[q],g.origType.replace(ha,"")===a.type?f.push(g.selector):s.splice(q--,1);f=c(a.target).closest(f,a.currentTarget);k=0;for(m=f.length;k<m;k++){h=f[k];for(q=0;q<s.length;q++)if(g=s[q],h.selector===g.selector&&(!l||l.test(g.namespace))&&!h.elem.disabled){j=h.elem;e=null;if(g.preType==="mouseenter"||g.preType==="mouseleave")a.type=g.preType,(e=c(a.relatedTarget).closest(g.selector)[0])&&c.contains(j,e)&&(e=j);(!e||e!==j)&&n.push({elem:j,
handleObj:g,level:h.level})}}k=0;for(m=n.length;k<m;k++){f=n[k];if(d&&f.level>d)break;a.currentTarget=f.elem;a.data=f.handleObj.data;a.handleObj=f.handleObj;l=f.handleObj.origHandler.apply(f.elem,arguments);if(l===!1||a.isPropagationStopped())if(d=f.level,l===!1&&(b=!1),a.isImmediatePropagationStopped())break}return b}}function w(a,b){return(a&&a!=="*"?a+".":"")+b.replace(bb,"`").replace(cb,"&")}function ba(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)===d});
else if(b.nodeType)return c.grep(a,function(a){return a===b===d});else if(typeof b==="string"){var e=c.grep(a,function(a){return a.nodeType===1});if(db.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(a){return c.inArray(a,b)>=0===d})}function H(a,b){if(b.nodeType===1&&c.hasData(a)){var d=c.expando,e=c.data(a),f=c.data(b,e);if(e=e[d]){var g=e.events,f=f[d]=c.extend({},e);if(g){delete f.handle;f.events={};for(var j in g){d=0;for(e=g[j].length;d<e;d++)c.event.add(b,j+(g[j][d].namespace?
".":"")+g[j][d].namespace,g[j][d],g[j][d].data)}}}}}function X(a,b){var d;if(b.nodeType===1){b.clearAttributes&&b.clearAttributes();b.mergeAttributes&&b.mergeAttributes(a);d=b.nodeName.toLowerCase();if(d==="object")b.outerHTML=a.outerHTML;else if(d==="input"&&(a.type==="checkbox"||a.type==="radio")){if(a.checked)b.defaultChecked=b.checked=a.checked;if(b.value!==a.value)b.value=a.value}else if(d==="option")b.selected=a.defaultSelected;else if(d==="input"||d==="textarea")b.defaultValue=a.defaultValue;
b.removeAttribute(c.expando)}}function A(a){return"getElementsByTagName"in a?a.getElementsByTagName("*"):"querySelectorAll"in a?a.querySelectorAll("*"):[]}function K(a){if(a.type==="checkbox"||a.type==="radio")a.defaultChecked=a.checked}function I(a){c.nodeName(a,"input")?K(a):a.getElementsByTagName&&c.grep(a.getElementsByTagName("input"),K)}function eb(a,b){b.src?c.ajax({url:b.src,async:!1,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}
function wa(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight;if(d==="border")return e;c.each(b==="width"?fb:gb,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);d==="margin"?e+=parseFloat(c.css(a,"margin"+this))||0:e-=parseFloat(c.css(a,"border"+this+"Width"))||0});return e}function xa(a){return function(b,d){var m;typeof b!=="string"&&(d=b,b="*");if(c.isFunction(d))for(var e=b.toLowerCase().split(ya),f=0,g=e.length,j,q;f<g;f++)j=e[f],(q=/^\+/.test(j))&&(j=j.substr(1)||"*"),m=a[j]=a[j]||
[],j=m,j[q?"unshift":"push"](d)}}function ca(a,b,c,e,f,g){f=f||b.dataTypes[0];g=g||{};g[f]=!0;for(var f=a[f],j=0,q=f?f.length:0,p=a===ia,m;j<q&&(p||!m);j++)m=f[j](b,c,e),typeof m==="string"&&(!p||g[m]?m=k:(b.dataTypes.unshift(m),m=ca(a,b,c,e,m,g)));if((p||!m)&&!g["*"])m=ca(a,b,c,e,"*",g);return m}function ja(a,b,d,e){if(c.isArray(b))c.each(b,function(b,f){d||hb.test(a)?e(a,f):ja(a+"["+(typeof f==="object"||c.isArray(f)?b:"")+"]",f,d,e)});else if(!d&&b!=null&&typeof b==="object")for(var f in b)ja(a+
"["+f+"]",b[f],d,e);else e(a,b)}function za(){try{return new h.XMLHttpRequest}catch(a){}}function Aa(){setTimeout(ib,0);return da=c.now()}function ib(){da=k}function M(a,b){var d={};c.each(Ba.concat.apply([],Ba.slice(0,b)),function(){d[this]=a});return d}function Ca(a){if(!ka[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if(d==="none"||d===""){if(!D)D=l.createElement("iframe"),D.frameBorder=D.width=D.height=0;l.body.appendChild(D);if(!Y||!D.createElement)Y=(D.contentWindow||
D.contentDocument).document,Y.write("<!doctype><html><body></body></html>");b=Y.createElement(a);Y.body.appendChild(b);d=c.css(b,"display");l.body.removeChild(D)}ka[a]=d}return ka[a]}function la(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}var l=h.document,jb=h.navigator,kb=h.location,c=function(){function a(){if(!b.isReady){try{l.documentElement.doScroll("left")}catch(c){setTimeout(a,1);return}b.ready()}}var b=function(a,c){return new b.fn.init(a,c,f)},c=h.jQuery,e=h.$,
f,g=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,j=/\S/,q=/^\s+/,p=/\s+$/,m=/\d/,o=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,n=/^[\],:{}\s]*$/,ab=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,s=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,z=/(?:^|:|,)(?:\s*\[)+/g,t=/(webkit)[ \/]([\w.]+)/,lb=/(opera)(?:.*version)?[ \/]([\w.]+)/,S=/(msie) ([\w.]+)/,v=/(mozilla)(?:.*? rv:([\w.]+))?/,u=jb.userAgent,r,J,mb=Object.prototype.toString,ma=Object.prototype.hasOwnProperty,na=Array.prototype.push,Z=Array.prototype.slice,
Da=String.prototype.trim,Ea=Array.prototype.indexOf,y={};b.fn=b.prototype={constructor:b,init:function(a,c,d){var e;if(!a)return this;if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if(a==="body"&&!c&&l.body)return this.context=l,this[0]=l.body,this.selector=a,this.length=1,this;if(typeof a==="string")if((e=a.charAt(0)==="<"&&a.charAt(a.length-1)===">"&&a.length>=3?[null,a,null]:g.exec(a))&&(e[1]||!c))if(e[1])return d=(c=c instanceof b?c[0]:c)?c.ownerDocument||c:l,(a=o.exec(a))?b.isPlainObject(c)?
(a=[l.createElement(a[1])],b.fn.attr.call(a,c,!0)):a=[d.createElement(a[1])]:(a=b.buildFragment([e[1]],[d]),a=(a.cacheable?b.clone(a.fragment):a.fragment).childNodes),b.merge(this,a);else{if((c=l.getElementById(e[2]))&&c.parentNode){if(c.id!==e[2])return d.find(a);this.length=1;this[0]=c}this.context=l;this.selector=a;return this}else return!c||c.jquery?(c||d).find(a):this.constructor(c).find(a);else if(b.isFunction(a))return d.ready(a);if(a.selector!==k)this.selector=a.selector,this.context=a.context;
return b.makeArray(a,this)},selector:"",jquery:"1.6",length:0,size:function(){return this.length},toArray:function(){return Z.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this[this.length+a]:this[a]},pushStack:function(a,c,d){var e=this.constructor();b.isArray(a)?na.apply(e,a):b.merge(e,a);e.prevObject=this;e.context=this.context;if(c==="find")e.selector=this.selector+(this.selector?" ":"")+d;else if(c)e.selector=this.selector+"."+c+"("+d+")";return e},each:function(a,c){return b.each(this,
a,c)},ready:function(a){b.bindReady();r.done(a);return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(Z.apply(this,arguments),"slice",Z.call(arguments).join(","))},map:function(a){return this.pushStack(b.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:na,sort:[].sort,splice:[].splice};b.fn.init.prototype=
b.fn;b.extend=b.fn.extend=function(){var a,c,d,e,f,g=arguments[0]||{},u=1,j=arguments.length,r=!1;typeof g==="boolean"&&(r=g,g=arguments[1]||{},u=2);typeof g!=="object"&&!b.isFunction(g)&&(g={});j===u&&(g=this,--u);for(;u<j;u++)if((a=arguments[u])!=null)for(c in a)d=g[c],e=a[c],g!==e&&(r&&e&&(b.isPlainObject(e)||(f=b.isArray(e)))?(f?(f=!1,d=d&&b.isArray(d)?d:[]):d=d&&b.isPlainObject(d)?d:{},g[c]=b.extend(r,d,e)):e!==k&&(g[c]=e));return g};b.extend({noConflict:function(a){if(h.$===b)h.$=e;if(a&&h.jQuery===
b)h.jQuery=c;return b},isReady:!1,readyWait:1,holdReady:function(a){a?b.readyWait++:b.ready(!0)},ready:function(a){if(a===!0&&!--b.readyWait||a!==!0&&!b.isReady){if(!l.body)return setTimeout(b.ready,1);b.isReady=!0;a!==!0&&--b.readyWait>0||(r.resolveWith(l,[b]),b.fn.trigger&&b(l).trigger("ready").unbind("ready"))}},bindReady:function(){if(!r){r=b._Deferred();if(l.readyState==="complete")return setTimeout(b.ready,1);if(l.addEventListener)l.addEventListener("DOMContentLoaded",J,!1),h.addEventListener("load",
b.ready,!1);else if(l.attachEvent){l.attachEvent("onreadystatechange",J);h.attachEvent("onload",b.ready);var c=!1;try{c=h.frameElement==null}catch(d){}l.documentElement.doScroll&&c&&a()}}},isFunction:function(a){return b.type(a)==="function"},isArray:Array.isArray||function(a){return b.type(a)==="array"},isWindow:function(a){return a&&typeof a==="object"&&"setInterval"in a},isNaN:function(a){return a==null||!m.test(a)||isNaN(a)},type:function(a){return a==null?String(a):y[mb.call(a)]||"object"},isPlainObject:function(a){if(!a||
b.type(a)!=="object"||a.nodeType||b.isWindow(a))return!1;if(a.constructor&&!ma.call(a,"constructor")&&!ma.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(var c in a);return c===k||ma.call(a,c)},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=b.trim(a);if(h.JSON&&h.JSON.parse)return h.JSON.parse(a);if(n.test(a.replace(ab,"@").replace(s,"]").replace(z,"")))return(new Function("return "+
a))();b.error("Invalid JSON: "+a)},parseXML:function(a,c,d){h.DOMParser?(d=new DOMParser,c=d.parseFromString(a,"text/xml")):(c=new ActiveXObject("Microsoft.XMLDOM"),c.async="false",c.loadXML(a));d=c.documentElement;(!d||!d.nodeName||d.nodeName==="parsererror")&&b.error("Invalid XML: "+a);return c},noop:function(){},globalEval:function(a){a&&j.test(a)&&(h.execScript||function(a){h.eval.call(h,a)})(a)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,
c,d){var e,f=0,g=a.length,u=g===k||b.isFunction(a);if(d)if(u)for(e in a){if(c.apply(a[e],d)===!1)break}else for(;f<g;){if(c.apply(a[f++],d)===!1)break}else if(u)for(e in a){if(c.call(a[e],e,a[e])===!1)break}else for(;f<g;)if(c.call(a[f],f,a[f++])===!1)break;return a},trim:Da?function(a){return a==null?"":Da.call(a)}:function(a){return a==null?"":a.toString().replace(q,"").replace(p,"")},makeArray:function(a,c){var d=c||[];if(a!=null){var e=b.type(a);a.length==null||e==="string"||e==="function"||e===
"regexp"||b.isWindow(a)?na.call(d,a):b.merge(d,a)}return d},inArray:function(a,b){if(Ea)return Ea.call(b,a);for(var c=0,d=b.length;c<d;c++)if(b[c]===a)return c;return-1},merge:function(a,b){var c=a.length,d=0;if(typeof b.length==="number")for(var e=b.length;d<e;d++)a[c++]=b[d];else for(;b[d]!==k;)a[c++]=b[d++];a.length=c;return a},grep:function(a,b,c){for(var d=[],e,c=!!c,f=0,g=a.length;f<g;f++)e=!!b(a[f],f),c!==e&&d.push(a[f]);return d},map:function(a,c,d){var e,f,g=[],u=0,j=a.length;if(a instanceof
b||j!==k&&typeof j==="number"&&(j>0&&a[0]&&a[j-1]||j===0||b.isArray(a)))for(;u<j;u++)e=c(a[u],u,d),e!=null&&(g[g.length]=e);else for(f in a)e=c(a[f],f,d),e!=null&&(g[g.length]=e);return g.concat.apply([],g)},guid:1,proxy:function(a,c){if(typeof c==="string")var d=a[c],c=a,a=d;if(!b.isFunction(a))return k;var e=Z.call(arguments,2),d=function(){return a.apply(c,e.concat(Z.call(arguments)))};d.guid=a.guid=a.guid||d.guid||b.guid++;return d},access:function(a,c,d,e,f,g){var u=a.length;if(typeof c==="object"){for(var j in c)b.access(a,
j,c[j],e,f,d);return a}if(d!==k){e=!g&&e&&b.isFunction(d);for(j=0;j<u;j++)f(a[j],c,e?d.call(a[j],j,f(a[j],c)):d,g);return a}return u?f(a[0],c):k},now:function(){return(new Date).getTime()},uaMatch:function(a){a=a.toLowerCase();a=t.exec(a)||lb.exec(a)||S.exec(a)||a.indexOf("compatible")<0&&v.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},sub:function(){function a(b,c){return new a.fn.init(b,c)}b.extend(!0,a,this);a.superclass=this;a.fn=a.prototype=this();a.fn.constructor=a;a.sub=this.sub;
a.fn.init=function(d,e){e&&e instanceof b&&!(e instanceof a)&&(e=a(e));return b.fn.init.call(this,d,e,c)};a.fn.init.prototype=a.fn;var c=a(l);return a},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(a,b){y["[object "+b+"]"]=b.toLowerCase()});u=b.uaMatch(u);if(u.browser)b.browser[u.browser]=!0,b.browser.version=u.version;if(b.browser.webkit)b.browser.safari=!0;j.test("\u00a0")&&(q=/^[\s\xA0]+/,p=/[\s\xA0]+$/);f=b(l);l.addEventListener?J=function(){l.removeEventListener("DOMContentLoaded",
J,!1);b.ready()}:l.attachEvent&&(J=function(){l.readyState==="complete"&&(l.detachEvent("onreadystatechange",J),b.ready())});return b}(),oa="done fail isResolved isRejected promise then always pipe".split(" "),Fa=[].slice;c.extend({_Deferred:function(){var a=[],b,d,e,f={done:function(){if(!e){var d=arguments,j,q,k,m,h;b&&(h=b,b=0);j=0;for(q=d.length;j<q;j++)k=d[j],m=c.type(k),m==="array"?f.done.apply(f,k):m==="function"&&a.push(k);h&&f.resolveWith(h[0],h[1])}return this},resolveWith:function(c,f){if(!e&&
!b&&!d){f=f||[];d=1;try{for(;a[0];)a.shift().apply(c,f)}finally{b=[c,f],d=0}}return this},resolve:function(){f.resolveWith(this,arguments);return this},isResolved:function(){return!(!d&&!b)},cancel:function(){e=1;a=[];return this}};return f},Deferred:function(a){var b=c._Deferred(),d=c._Deferred(),e;c.extend(b,{then:function(a,c){b.done(a).fail(c);return this},always:function(){return b.done.apply(b,arguments).fail.apply(this,arguments)},fail:d.done,rejectWith:d.resolveWith,reject:d.resolve,isRejected:d.isResolved,
pipe:function(a,d){return c.Deferred(function(e){c.each({done:[a,"resolve"],fail:[d,"reject"]},function(a,d){var f=d[0],g=d[1],k;if(c.isFunction(f))b[a](function(){k=f.apply(this,arguments);if(c.isFunction(k.promise))k.promise().then(e.resolve,e.reject);else e[g](k)});else b[a](e[g])})}).promise()},promise:function(a){if(a==null){if(e)return e;e=a={}}for(var c=oa.length;c--;)a[oa[c]]=b[oa[c]];return a}});b.done(d.cancel).fail(b.cancel);delete b.cancel;a&&a.call(b,b);return b},when:function(a){function b(a){return function(b){d[a]=
arguments.length>1?Fa.call(arguments,0):b;--g||j.resolveWith(j,Fa.call(d,0))}}var d=arguments,e=0,f=d.length,g=f,j=f<=1&&a&&c.isFunction(a.promise)?a:c.Deferred();if(f>1){for(;e<f;e++)d[e]&&c.isFunction(d[e].promise)?d[e].promise().then(b(e),j.reject):--g;g||j.resolveWith(j,d)}else j!==a&&j.resolveWith(j,f?[a]:[]);return j.promise()}});c.support=function(){var a=l.createElement("div"),b,c,e,f,g,j;a.setAttribute("className","t");a.innerHTML="   <link/><table></table><a href='/a' style='top:1px;float:left;opacity:.55;'>a</a><input type='checkbox'/>";
b=a.getElementsByTagName("*");c=a.getElementsByTagName("a")[0];if(!b||!b.length||!c)return{};e=l.createElement("select");f=e.appendChild(l.createElement("option"));b=a.getElementsByTagName("input")[0];g={leadingWhitespace:a.firstChild.nodeType===3,tbody:!a.getElementsByTagName("tbody").length,htmlSerialize:!!a.getElementsByTagName("link").length,style:/top/.test(c.getAttribute("style")),hrefNormalized:c.getAttribute("href")==="/a",opacity:/^0.55$/.test(c.style.opacity),cssFloat:!!c.style.cssFloat,
checkOn:b.value==="on",optSelected:f.selected,getSetAttribute:a.className!=="t",submitBubbles:!0,changeBubbles:!0,focusinBubbles:!1,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,reliableMarginRight:!0};b.checked=!0;g.noCloneChecked=b.cloneNode(!0).checked;e.disabled=!0;g.optDisabled=!f.disabled;try{delete a.test}catch(k){g.deleteExpando=!1}!a.addEventListener&&a.attachEvent&&a.fireEvent&&(a.attachEvent("onclick",function m(){g.noCloneEvent=!1;a.detachEvent("onclick",
m)}),a.cloneNode(!0).fireEvent("onclick"));b=l.createElement("input");b.value="t";b.setAttribute("type","radio");g.radioValue=b.value==="t";b.setAttribute("checked","checked");a.appendChild(b);c=l.createDocumentFragment();c.appendChild(a.firstChild);g.checkClone=c.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="";a.style.width=a.style.paddingLeft="1px";c=l.createElement("body");e={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};for(j in e)c.style[j]=e[j];c.appendChild(a);
l.documentElement.appendChild(c);g.appendChecked=b.checked;g.boxModel=a.offsetWidth===2;if("zoom"in a.style)a.style.display="inline",a.style.zoom=1,g.inlineBlockNeedsLayout=a.offsetWidth===2,a.style.display="",a.innerHTML="<div style='width:4px;'></div>",g.shrinkWrapBlocks=a.offsetWidth!==2;a.innerHTML="<table><tr><td style='padding:0;border:0;display:none'></td><td>t</td></tr></table>";e=a.getElementsByTagName("td");b=e[0].offsetHeight===0;e[0].style.display="";e[1].style.display="none";g.reliableHiddenOffsets=
b&&e[0].offsetHeight===0;a.innerHTML="";if(l.defaultView&&l.defaultView.getComputedStyle)b=l.createElement("div"),b.style.width="0",b.style.marginRight="0",a.appendChild(b),g.reliableMarginRight=(parseInt(l.defaultView.getComputedStyle(b,null).marginRight,10)||0)===0;c.innerHTML="";l.documentElement.removeChild(c);if(a.attachEvent)for(j in{submit:1,change:1,focusin:1})c="on"+j,b=c in a,b||(a.setAttribute(c,"return;"),b=typeof a[c]==="function"),g[j+"Bubbles"]=b;return g}();c.boxModel=c.support.boxModel;
var $a=/^(?:\{.*\}|\[.*\])$/,Za=/([a-z])([A-Z])/g;c.extend({cache:{},uuid:0,expando:"jQuery"+(c.fn.jquery+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:a[c.expando];return!!a&&!v(a)},data:function(a,b,d,e){if(c.acceptData(a)){var f=c.expando,g=typeof b==="string",j=a.nodeType,q=j?c.cache:a,h=j?a[c.expando]:a[c.expando]&&c.expando;if(h&&(!e||!h||q[h][f])||!(g&&d===k)){if(!h)j?a[c.expando]=
h=++c.uuid:h=c.expando;if(!q[h]&&(q[h]={},!j))q[h].toJSON=c.noop;if(typeof b==="object"||typeof b==="function")e?q[h][f]=c.extend(q[h][f],b):q[h]=c.extend(q[h],b);a=q[h];e&&(a[f]||(a[f]={}),a=a[f]);d!==k&&(a[b]=d);if(b==="events"&&!a[b])return a[f]&&a[f].events;return g?a[b]:a}}},removeData:function(a,b,d){if(c.acceptData(a)){var e=c.expando,f=a.nodeType,g=f?c.cache:a,j=f?a[c.expando]:c.expando;if(g[j]){if(b){var k=d?g[j][e]:g[j];if(k&&(delete k[b],!v(k)))return}if(d&&(delete g[j][e],!v(g[j])))return;
b=g[j][e];c.support.deleteExpando||g!=h?delete g[j]:g[j]=null;if(b){g[j]={};if(!f)g[j].toJSON=c.noop;g[j][e]=b}else f&&(c.support.deleteExpando?delete a[c.expando]:a.removeAttribute?a.removeAttribute(c.expando):a[c.expando]=null)}}},_data:function(a,b,d){return c.data(a,b,d,!0)},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];if(b)return!(b===!0||a.getAttribute("classid")!==b)}return!0}});c.fn.extend({data:function(a,b){var d=null;if(typeof a==="undefined"){if(this.length&&
(d=c.data(this[0]),this[0].nodeType===1))for(var e=this[0].attributes,f,g=0,j=e.length;g<j;g++)f=e[g].name,f.indexOf("data-")===0&&(f=c.camelCase(f.substring(5)),n(this[0],f,d[f]));return d}else if(typeof a==="object")return this.each(function(){c.data(this,a)});var h=a.split(".");h[1]=h[1]?"."+h[1]:"";return b===k?(d=this.triggerHandler("getData"+h[1]+"!",[h[0]]),d===k&&this.length&&(d=c.data(this[0],a),d=n(this[0],a,d)),d===k&&h[1]?this.data(h[0]):d):this.each(function(){var d=c(this),e=[h[0],b];
d.triggerHandler("setData"+h[1]+"!",e);c.data(this,a,b);d.triggerHandler("changeData"+h[1]+"!",e)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({_mark:function(a,b){a&&(b=(b||"fx")+"mark",c.data(a,b,(c.data(a,b,k,!0)||0)+1,!0))},_unmark:function(a,b,d){a!==!0&&(d=b,b=a,a=!1);if(b){var d=d||"fx",e=d+"mark";(a=a?0:(c.data(b,e,k,!0)||1)-1)?c.data(b,e,a,!0):(c.removeData(b,e,!0),t(b,d,"mark"))}},queue:function(a,b,d){if(a){var b=(b||"fx")+"queue",e=c.data(a,
b,k,!0);d&&(!e||c.isArray(d)?e=c.data(a,b,c.makeArray(d),!0):e.push(d));return e||[]}},dequeue:function(a,b){var b=b||"fx",d=c.queue(a,b),e=d.shift();e==="inprogress"&&(e=d.shift());e&&(b==="fx"&&d.unshift("inprogress"),e.call(a,function(){c.dequeue(a,b)}));d.length||(c.removeData(a,b+"queue",!0),t(a,b,"queue"))}});c.fn.extend({queue:function(a,b){typeof a!=="string"&&(b=a,a="fx");if(b===k)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&
c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a){function b(){--g||d.resolveWith(e,[e])}typeof a!=="string"&&(a=k);var a=a||"fx",d=c.Deferred(),e=this,f=e.length,g=1,j=a+"defer",h=a+"queue";for(a+="mark";f--;)if(tmp=c.data(e[f],j,k,!0)||(c.data(e[f],
h,k,!0)||c.data(e[f],a,k,!0))&&c.data(e[f],j,c._Deferred(),!0))g++,tmp.done(b);b();return d.promise()}});var Ga=/[\n\t\r]/g,pa=/\s+/,nb=/\r/g,ob=/^(?:button|input)$/i,pb=/^(?:button|input|object|select|textarea)$/i,qb=/^a(?:rea)?$/i,Ha=/^(?:data-|aria-)/,rb=/\:/,qa;c.fn.extend({attr:function(a,b){return c.access(this,a,b,!0,c.attr)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},prop:function(a,b){return c.access(this,a,b,!0,c.prop)},removeProp:function(a){return this.each(function(){try{this[a]=
k,delete this[a]}catch(b){}})},addClass:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.addClass(a.call(this,b,d.attr("class")||""))});if(a&&typeof a==="string")for(var b=(a||"").split(pa),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1)if(f.className){for(var g=" "+f.className+" ",j=f.className,k=0,h=b.length;k<h;k++)g.indexOf(" "+b[k]+" ")<0&&(j+=" "+b[k]);f.className=c.trim(j)}else f.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(b){var d=
c(this);d.removeClass(a.call(this,b,d.attr("class")))});if(a&&typeof a==="string"||a===k)for(var b=(a||"").split(pa),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1&&f.className)if(a){for(var g=(" "+f.className+" ").replace(Ga," "),j=0,h=b.length;j<h;j++)g=g.replace(" "+b[j]+" "," ");f.className=c.trim(g)}else f.className=""}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(d){var e=c(this);e.toggleClass(a.call(this,
d,e.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var f,g=0,j=c(this),k=b,h=a.split(pa);f=h[g++];)k=e?k:!j.hasClass(f),j[k?"addClass":"removeClass"](f);else if(d==="undefined"||d==="boolean")this.className&&c._data(this,"__className__",this.className),this.className=this.className||a===!1?"":c._data(this,"__className__")||""})},hasClass:function(a){for(var a=" "+a+" ",b=0,c=this.length;b<c;b++)if((" "+this[b].className+" ").replace(Ga," ").indexOf(a)>-1)return!0;return!1},
val:function(a){var b,d,e=this[0];if(!arguments.length){if(e){if((b=c.valHooks[e.nodeName.toLowerCase()]||c.valHooks[e.type])&&"get"in b&&(d=b.get(e,"value"))!==k)return d;return(e.value||"").replace(nb,"")}return k}var f=c.isFunction(a);return this.each(function(d){var e=c(this);if(this.nodeType===1&&(d=f?a.call(this,d,e.val()):a,d==null?d="":typeof d==="number"?d+="":c.isArray(d)&&(d=c.map(d,function(a){return a==null?"":a+""})),b=c.valHooks[this.nodeName.toLowerCase()]||c.valHooks[this.type],!b||
"set"in b&&b.set(this,d,"value")===k))this.value=d})}});c.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){var b=a.selectedIndex,d=[],e=a.options,a=a.type==="select-one";if(b<0)return null;for(var f=a?b:0,g=a?b+1:e.length;f<g;f++){var j=e[f];if(j.selected&&(c.support.optDisabled?!j.disabled:j.getAttribute("disabled")===null)&&(!j.parentNode.disabled||!c.nodeName(j.parentNode,"optgroup"))){value=c(j).val();if(a)return value;
d.push(value)}}if(a&&!d.length&&e.length)return c(e[b]).val();return d},set:function(a,b){var d=c.makeArray(b);c(a).find("option").each(function(){this.selected=c.inArray(c(this).val(),d)>=0});if(!d.length)a.selectedIndex=-1;return d}}},attrFn:{val:!0,css:!0,html:!0,text:!0,data:!0,width:!0,height:!0,offset:!0},attrFix:{tabindex:"tabIndex",readonly:"readOnly"},attr:function(a,b,d,e){var f=a.nodeType;if(!a||f===3||f===8||f===2)return k;if(e&&b in c.attrFn)return c(a)[b](d);var g,b=(f=f!==1||!c.isXMLDoc(a))&&
c.attrFix[b]||b,e=c.attrHooks[b]||(qa&&(c.nodeName(a,"form")||rb.test(b))?qa:k);return d!==k?d===null||d===!1&&!Ha.test(b)?(c.removeAttr(a,b),k):e&&"set"in e&&f&&(g=e.set(a,d,b))!==k?g:(d===!0&&!Ha.test(b)&&(d=b),a.setAttribute(b,""+d),d):e&&"get"in e&&f?e.get(a,b):(g=a.getAttribute(b),g===null?k:g)},removeAttr:function(a,b){a.nodeType===1&&(b=c.attrFix[b]||b,c.support.getSetAttribute?a.removeAttribute(b):(c.attr(a,b,""),a.removeAttributeNode(a.getAttributeNode(b))))},attrHooks:{type:{set:function(a,
b){if(ob.test(a.nodeName)&&a.parentNode)c.error("type property can't be changed");else if(!c.support.radioValue&&b==="radio"&&c.nodeName(a,"input")){var d=a.getAttribute("value");a.setAttribute("type",b);if(d)a.value=d;return b}}},tabIndex:{get:function(a){var b=a.getAttributeNode("tabIndex");return b&&b.specified?parseInt(b.value,10):pb.test(a.nodeName)||qb.test(a.nodeName)&&a.href?0:k}}},propFix:{},prop:function(a,b,d){var e=a.nodeType;if(!a||e===3||e===8||e===2)return k;var f,b=(e!==1||!c.isXMLDoc(a))&&
c.propFix[b]||b,e=c.propHooks[b];return d!==k?e&&"set"in e&&(f=e.set(a,d,b))!==k?f:a[b]=d:e&&"get"in e&&(f=e.get(a,b))!==k?f:a[b]},propHooks:{}});if(!c.support.getSetAttribute)c.attrFix=c.extend(c.attrFix,{"for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder"}),qa=c.attrHooks.name=c.attrHooks.value=c.valHooks.button={get:function(a,b){var d;if(b==="value"&&!c.nodeName(a,
"button"))return a.getAttribute(b);return(d=a.getAttributeNode(b))&&d.specified?d.nodeValue:k},set:function(a,b,c){if(a=a.getAttributeNode(c))return a.nodeValue=b}},c.each(["width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(a,c){if(c==="")return a.setAttribute(b,"auto"),c}})});c.support.hrefNormalized||c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(a){a=a.getAttribute(b,2);return a===null?k:a}})});if(!c.support.style)c.attrHooks.style=
{get:function(a){return a.style.cssText.toLowerCase()||k},set:function(a,b){return a.style.cssText=""+b}};if(!c.support.optSelected)c.propHooks.selected=c.extend(c.propHooks.selected,{get:function(){}});c.support.checkOn||c.each(["radio","checkbox"],function(){c.valHooks[this]={get:function(a){return a.getAttribute("value")===null?"on":a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],{set:function(a,b){if(c.isArray(b))return a.checked=c.inArray(c(a).val(),
b)>=0}})});var ha=/\.(.*)$/,ra=/^(?:textarea|input|select)$/i,bb=/\./g,cb=/ /g,sb=/[^\w\s.|`]/g,tb=function(a){return a.replace(sb,"\\$&")};c.event={add:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){if(d===!1)d=y;else if(!d)return;var f,g;if(d.handler)f=d,d=f.handler;if(!d.guid)d.guid=c.guid++;if(g=c._data(a)){var j=g.events,h=g.handle;if(!j)g.events=j={};if(!h)g.handle=h=function(a){return typeof c!=="undefined"&&(!a||c.event.triggered!==a.type)?c.event.handle.apply(h.elem,arguments):k};
h.elem=a;for(var b=b.split(" "),p,m=0,o;p=b[m++];){g=f?c.extend({},f):{handler:d,data:e};p.indexOf(".")>-1?(o=p.split("."),p=o.shift(),g.namespace=o.slice(0).sort().join(".")):(o=[],g.namespace="");g.type=p;if(!g.guid)g.guid=d.guid;var l=j[p],n=c.event.special[p]||{};if(!l&&(l=j[p]=[],!n.setup||n.setup.call(a,e,o,h)===!1))a.addEventListener?a.addEventListener(p,h,!1):a.attachEvent&&a.attachEvent("on"+p,h);if(n.add&&(n.add.call(a,g),!g.handler.guid))g.handler.guid=d.guid;l.push(g);c.event.global[p]=
!0}a=null}}},global:{},remove:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){d===!1&&(d=y);var f,g,j=0,h,p,m,o,l,n,s=c.hasData(a)&&c._data(a),z=s&&s.events;if(s&&z){if(b&&b.type)d=b.handler,b=b.type;if(!b||typeof b==="string"&&b.charAt(0)===".")for(f in b=b||"",z)c.event.remove(a,f+b);else{for(b=b.split(" ");f=b[j++];)if(o=f,h=f.indexOf(".")<0,p=[],h||(p=f.split("."),f=p.shift(),m=RegExp("(^|\\.)"+c.map(p.slice(0).sort(),tb).join("\\.(?:.*\\.)?")+"(\\.|$)")),l=z[f])if(d){o=c.event.special[f]||
{};for(g=e||0;g<l.length;g++)if(n=l[g],d.guid===n.guid){if(h||m.test(n.namespace))e==null&&l.splice(g--,1),o.remove&&o.remove.call(a,n);if(e!=null)break}if(l.length===0||e!=null&&l.length===1)(!o.teardown||o.teardown.call(a,p)===!1)&&c.removeEvent(a,f,s.handle),delete z[f]}else for(g=0;g<l.length;g++)if(n=l[g],h||m.test(n.namespace))c.event.remove(a,o,n.handler,g),l.splice(g--,1);if(c.isEmptyObject(z)){if(b=s.handle)b.elem=null;delete s.events;delete s.handle;c.isEmptyObject(s)&&c.removeData(a,k,
!0)}}}}},customEvent:{getData:!0,setData:!0,changeData:!0},trigger:function(a,b,d,e){var f=a.type||a,g=[],j;f.indexOf("!")>=0&&(f=f.slice(0,-1),j=!0);f.indexOf(".")>=0&&(g=f.split("."),f=g.shift(),g.sort());if(d&&!c.event.customEvent[f]||c.event.global[f]){a=typeof a==="object"?a[c.expando]?a:new c.Event(f,a):new c.Event(f);a.type=f;a.exclusive=j;a.namespace=g.join(".");a.namespace_re=RegExp("(^|\\.)"+g.join("\\.(?:.*\\.)?")+"(\\.|$)");if(e||!d)a.preventDefault(),a.stopPropagation();if(d){if(!(d.nodeType===
3||d.nodeType===8)){a.result=k;a.target=d;b=b?c.makeArray(b):[];b.unshift(a);g=d;e=f.indexOf(":")<0?"on"+f:"";do{j=c._data(g,"handle");a.currentTarget=g;j&&j.apply(g,b);if(e&&c.acceptData(g)&&g[e]&&g[e].apply(g,b)===!1)a.result=!1,a.preventDefault();g=g.parentNode||g.ownerDocument||g===a.target.ownerDocument&&h}while(g&&!a.isPropagationStopped());if(!a.isDefaultPrevented()){var q,g=c.event.special[f]||{};if((!g._default||g._default.call(d.ownerDocument,a)===!1)&&!(f==="click"&&c.nodeName(d,"a"))&&
c.acceptData(d)){try{if(e&&d[f])(q=d[e])&&(d[e]=null),c.event.triggered=f,d[f]()}catch(p){}q&&(d[e]=q);c.event.triggered=k}}return a.result}}else c.each(c.cache,function(){var d=this[c.expando];d&&d.events&&d.events[f]&&c.event.trigger(a,b,d.handle.elem)})}},handle:function(a){var a=c.event.fix(a||h.event),b=((c._data(this,"events")||{})[a.type]||[]).slice(0),d=!a.exclusive&&!a.namespace,e=Array.prototype.slice.call(arguments,0);e[0]=a;a.currentTarget=this;for(var f=0,g=b.length;f<g;f++){var j=b[f];
if(d||a.namespace_re.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,e);if(j!==k)a.result=j,j===!1&&(a.preventDefault(),a.stopPropagation());if(a.isImmediatePropagationStopped())break}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[c.expando])return a;for(var b=a,a=c.Event(b),d=this.props.length,e;d;)e=this.props[--d],a[e]=b[e];if(!a.target)a.target=a.srcElement||l;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null)d=a.target.ownerDocument||l,b=d.documentElement,d=d.body,a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0),a.pageY=
a.clientY+(b&&b.scrollTop||d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0);if(a.which==null&&(a.charCode!=null||a.keyCode!=null))a.which=a.charCode!=null?a.charCode:a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==k)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,w(a.origType,a.selector),c.extend({},a,{handler:G,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,
w(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};c.removeEvent=l.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)}:function(a,b,c){a.detachEvent&&a.detachEvent("on"+b,c)};c.Event=function(a,b){if(!this.preventDefault)return new c.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||
a.returnValue===!1||a.getPreventDefault&&a.getPreventDefault()?F:y):this.type=a;b&&c.extend(this,b);this.timeStamp=c.now();this[c.expando]=!0};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=F;var a=this.originalEvent;if(a)a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(){this.isPropagationStopped=F;var a=this.originalEvent;if(a)a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=
F;this.stopPropagation()},isDefaultPrevented:y,isPropagationStopped:y,isImmediatePropagationStopped:y};var Ia=function(a){var b=a.relatedTarget;try{if(!b||b===l||b.parentNode){for(;b&&b!==this;)b=b.parentNode;if(b!==this)a.type=a.data,c.event.handle.apply(this,arguments)}}catch(d){}},Ja=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Ja:Ia,a)},
teardown:function(a){c.event.remove(this,b,a&&a.selector?Ja:Ia)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return!1;else c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;(d==="submit"||d==="image")&&c(b).closest("form").length&&W("submit",this,arguments)}),c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;(d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13&&W("submit",
this,arguments)})},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var aa,Ka=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(a){return a.selected}).join("-"):"";else if(c.nodeName(a,"select"))d=a.selectedIndex;return d},ea=function(a,b){var d=a.target,e,f;if(ra.test(d.nodeName)&&!d.readOnly&&(e=c._data(d,"_change_data"),f=Ka(d),(a.type!=="focusout"||d.type!==
"radio")&&c._data(d,"_change_data",f),!(e===k||f===e)))if(e!=null||f)a.type="change",a.liveFired=k,c.event.trigger(a,b,d)};c.event.special.change={filters:{focusout:ea,beforedeactivate:ea,click:function(a){var b=a.target,d=c.nodeName(b,"input")?b.type:"";(d==="radio"||d==="checkbox"||c.nodeName(b,"select"))&&ea.call(this,a)},keydown:function(a){var b=a.target,d=c.nodeName(b,"input")?b.type:"";(a.keyCode===13&&!c.nodeName(b,"textarea")||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")&&
ea.call(this,a)},beforeactivate:function(a){a=a.target;c._data(a,"_change_data",Ka(a))}},setup:function(){if(this.type==="file")return!1;for(var a in aa)c.event.add(this,a+".specialChange",aa[a]);return ra.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return ra.test(this.nodeName)}};aa=c.event.special.change.filters;aa.focus=aa.beforeactivate}c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(a){var d=c.event.fix(a);d.type=
b;d.originalEvent={};c.event.trigger(d,null,d.target);d.isDefaultPrevented()&&a.preventDefault()}var e=0;c.event.special[b]={setup:function(){e++===0&&l.addEventListener(a,d,!0)},teardown:function(){--e===0&&l.removeEventListener(a,d,!0)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(a,e,f){var g;if(typeof a==="object"){for(var j in a)this[b](j,e,a[j],f);return this}if(arguments.length===2||e===!1)f=e,e=k;b==="one"?(g=function(a){c(this).unbind(a,g);return f.apply(this,arguments)},g.guid=
f.guid||c.guid++):g=f;if(a==="unload"&&b!=="one")this.one(a,e,f);else{j=0;for(var h=this.length;j<h;j++)c.event.add(this[j],a,g,e)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,c,e){return this.live(b,c,e,a)},undelegate:function(a,b,c){return arguments.length===0?this.unbind("live"):this.die(b,null,c,a)},trigger:function(a,
b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0])return c.event.trigger(a,b,this[0],!0)},toggle:function(a){var b=arguments,d=a.guid||c.guid++,e=0,f=function(d){var f=(c.data(this,"lastToggle"+a.guid)||0)%e;c.data(this,"lastToggle"+a.guid,f+1);d.preventDefault();return b[f].apply(this,arguments)||!1};for(f.guid=d;e<b.length;)b[e++].guid=d;return this.click(f)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var sa={focus:"focusin",
blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(a,e,f,g){var j=0,h,p,m=g||this.selector,l=g?this:c(this.context);if(typeof a==="object"&&!a.preventDefault){for(h in a)l[b](h,e,a[h],m);return this}if(b==="die"&&!a&&g&&g.charAt(0)===".")return l.unbind(g),this;if(e===!1||c.isFunction(e))f=e||y,e=k;for(a=(a||"").split(" ");(g=a[j++])!=null;)if(h=ha.exec(g),p="",h&&(p=h[0],g=g.replace(ha,"")),g==="hover")a.push("mouseenter"+p,"mouseleave"+
p);else if(h=g,sa[g]?(a.push(sa[g]+p),g+=p):g=(sa[g]||g)+p,b==="live"){p=0;for(var n=l.length;p<n;p++)c.event.add(l[p],"live."+w(g,m),{data:e,selector:m,handler:f,origType:g,origHandler:f,preType:h})}else l.unbind("live."+w(g,m),f);return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),function(a,b){c.fn[b]=function(a,c){c==null&&(c=
a,a=null);return arguments.length>0?this.bind(b,a,c):this.trigger(b)};c.attrFn&&(c.attrFn[b]=!0)});(function(){function a(a,b,c,d,e,f){for(var e=0,g=d.length;e<g;e++){var j=d[e];if(j){for(var h=!1,j=j[a];j;){if(j.sizcache===c){h=d[j.sizset];break}if(j.nodeType===1&&!f)j.sizcache=c,j.sizset=e;if(j.nodeName.toLowerCase()===b){h=j;break}j=j[a]}d[e]=h}}}function b(a,b,c,d,e,f){for(var e=0,g=d.length;e<g;e++){var j=d[e];if(j){for(var h=!1,j=j[a];j;){if(j.sizcache===c){h=d[j.sizset];break}if(j.nodeType===
1){if(!f)j.sizcache=c,j.sizset=e;if(typeof b!=="string"){if(j===b){h=!0;break}}else if(m.filter(b,[j]).length>0){h=j;break}}j=j[a]}d[e]=h}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,f=Object.prototype.toString,g=!1,j=!0,h=/\\/g,p=/\W/;[0,0].sort(function(){j=!1;return 0});var m=function(a,b,c,e){var c=c||[],g=b=b||l;if(b.nodeType!==1&&b.nodeType!==9)return[];if(!a||typeof a!=="string")return c;var j,
h,k,p,q,s=!0,t=m.isXML(b),x=[],y=a;do if(d.exec(""),j=d.exec(y))if(y=j[3],x.push(j[1]),j[2]){p=j[3];break}while(j);if(x.length>1&&n.exec(a))if(x.length===2&&o.relative[x[0]])h=w(x[0]+x[1],b);else for(h=o.relative[x[0]]?[b]:m(x.shift(),b);x.length;)a=x.shift(),o.relative[a]&&(a+=x.shift()),h=w(a,h);else if(!e&&x.length>1&&b.nodeType===9&&!t&&o.match.ID.test(x[0])&&!o.match.ID.test(x[x.length-1])&&(j=m.find(x.shift(),b,t),b=j.expr?m.filter(j.expr,j.set)[0]:j.set[0]),b){j=e?{expr:x.pop(),set:z(e)}:m.find(x.pop(),
x.length===1&&(x[0]==="~"||x[0]==="+")&&b.parentNode?b.parentNode:b,t);h=j.expr?m.filter(j.expr,j.set):j.set;for(x.length>0?k=z(h):s=!1;x.length;)j=q=x.pop(),o.relative[q]?j=x.pop():q="",j==null&&(j=b),o.relative[q](k,j,t)}else k=[];k||(k=h);k||m.error(q||a);if(f.call(k)==="[object Array]")if(s)if(b&&b.nodeType===1)for(a=0;k[a]!=null;a++)k[a]&&(k[a]===!0||k[a].nodeType===1&&m.contains(b,k[a]))&&c.push(h[a]);else for(a=0;k[a]!=null;a++)k[a]&&k[a].nodeType===1&&c.push(h[a]);else c.push.apply(c,k);else z(k,
c);p&&(m(p,g,c,e),m.uniqueSort(c));return c};m.uniqueSort=function(a){if(y&&(g=j,a.sort(y),g))for(var b=1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1);return a};m.matches=function(a,b){return m(a,null,null,b)};m.matchesSelector=function(a,b){return m(b,null,null,[a]).length>0};m.find=function(a,b,c){var d;if(!a)return[];for(var e=0,f=o.order.length;e<f;e++){var g,j=o.order[e];if(g=o.leftMatch[j].exec(a)){var k=g[1];g.splice(1,1);if(k.substr(k.length-1)!=="\\"&&(g[1]=(g[1]||"").replace(h,""),d=o.find[j](g,
b,c),d!=null)){a=a.replace(o.match[j],"");break}}}d||(d=typeof b.getElementsByTagName!=="undefined"?b.getElementsByTagName("*"):[]);return{set:d,expr:a}};m.filter=function(a,b,c,d){for(var e,f,g=a,j=[],h=b,p=b&&b[0]&&m.isXML(b[0]);a&&b.length;){for(var q in o.filter)if((e=o.leftMatch[q].exec(a))!=null&&e[2]){var l,n,s=o.filter[q];n=e[1];f=!1;e.splice(1,1);if(n.substr(n.length-1)!=="\\"){h===j&&(j=[]);if(o.preFilter[q])if(e=o.preFilter[q](e,h,c,j,d,p)){if(e===!0)continue}else f=l=!0;if(e)for(var t=
0;(n=h[t])!=null;t++)if(n){l=s(n,e,t,h);var z=d^!!l;c&&l!=null?z?f=!0:h[t]=!1:z&&(j.push(n),f=!0)}if(l!==k){c||(h=j);a=a.replace(o.match[q],"");if(!f)return[];break}}}if(a===g)if(f==null)m.error(a);else break;g=a}return h};m.error=function(a){throw"Syntax error, unrecognized expression: "+a;};var o=m.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")},type:function(a){return a.getAttribute("type")}},relative:{"+":function(a,b){var c=
typeof b==="string",d=c&&!p.test(b),c=c&&!d;d&&(b=b.toLowerCase());for(var d=0,e=a.length,f;d<e;d++)if(f=a[d]){for(;(f=f.previousSibling)&&f.nodeType!==1;);a[d]=c||f&&f.nodeName.toLowerCase()===b?f||!1:f===b}c&&m.filter(b,a,!0)},">":function(a,b){var c,d=typeof b==="string",e=0,f=a.length;if(d&&!p.test(b))for(b=b.toLowerCase();e<f;e++){if(c=a[e])c=c.parentNode,a[e]=c.nodeName.toLowerCase()===b?c:!1}else{for(;e<f;e++)(c=a[e])&&(a[e]=d?c.parentNode:c.parentNode===b);d&&m.filter(b,a,!0)}},"":function(c,
d,f){var g,j=e++,h=b;typeof d==="string"&&!p.test(d)&&(g=d=d.toLowerCase(),h=a);h("parentNode",d,j,c,g,f)},"~":function(c,d,f){var g,j=e++,h=b;typeof d==="string"&&!p.test(d)&&(g=d=d.toLowerCase(),h=a);h("previousSibling",d,j,c,g,f)}},find:{ID:function(a,b,c){if(typeof b.getElementById!=="undefined"&&!c)return(a=b.getElementById(a[1]))&&a.parentNode?[a]:[]},NAME:function(a,b){if(typeof b.getElementsByName!=="undefined"){for(var c=[],d=b.getElementsByName(a[1]),e=0,f=d.length;e<f;e++)d[e].getAttribute("name")===
a[1]&&c.push(d[e]);return c.length===0?null:c}},TAG:function(a,b){if(typeof b.getElementsByTagName!=="undefined")return b.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,b,c,d,e,f){a=" "+a[1].replace(h,"")+" ";if(f)return a;for(var f=0,g;(g=b[f])!=null;f++)g&&(e^(g.className&&(" "+g.className+" ").replace(/[\t\n\r]/g," ").indexOf(a)>=0)?c||d.push(g):c&&(b[f]=!1));return!1},ID:function(a){return a[1].replace(h,"")},TAG:function(a){return a[1].replace(h,"").toLowerCase()},CHILD:function(a){if(a[1]===
"nth"){a[2]||m.error(a[0]);a[2]=a[2].replace(/^\+|\s*/g,"");var b=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec(a[2]==="even"&&"2n"||a[2]==="odd"&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}else a[2]&&m.error(a[0]);a[0]=e++;return a},ATTR:function(a,b,c,d,e,f){b=a[1]=a[1].replace(h,"");!f&&o.attrMap[b]&&(a[1]=o.attrMap[b]);a[4]=(a[4]||a[5]||"").replace(h,"");a[2]==="~="&&(a[4]=" "+a[4]+" ");return a},PSEUDO:function(a,b,c,e,f){if(a[1]==="not")if((d.exec(a[3])||"").length>1||
/^\w/.test(a[3]))a[3]=m(a[3],null,null,b);else return a=m.filter(a[3],b,c,1^f),c||e.push.apply(e,a),!1;else if(o.match.POS.test(a[0])||o.match.CHILD.test(a[0]))return!0;return a},POS:function(a){a.unshift(!0);return a}},filters:{enabled:function(a){return a.disabled===!1&&a.type!=="hidden"},disabled:function(a){return a.disabled===!0},checked:function(a){return a.checked===!0},selected:function(a){return a.selected===!0},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},
has:function(a,b,c){return!!m(c[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){var b=a.getAttribute("type"),c=a.type;return a.nodeName.toLowerCase()==="input"&&"text"===c&&(b===c||b===null)},radio:function(a){return a.nodeName.toLowerCase()==="input"&&"radio"===a.type},checkbox:function(a){return a.nodeName.toLowerCase()==="input"&&"checkbox"===a.type},file:function(a){return a.nodeName.toLowerCase()==="input"&&"file"===a.type},password:function(a){return a.nodeName.toLowerCase()===
"input"&&"password"===a.type},submit:function(a){var b=a.nodeName.toLowerCase();return(b==="input"||b==="button")&&"submit"===a.type},image:function(a){return a.nodeName.toLowerCase()==="input"&&"image"===a.type},reset:function(a){return a.nodeName.toLowerCase()==="input"&&"reset"===a.type},button:function(a){var b=a.nodeName.toLowerCase();return b==="input"&&"button"===a.type||b==="button"},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)},focus:function(a){return a===a.ownerDocument.activeElement}},
setFilters:{first:function(a,b){return b===0},last:function(a,b,c,d){return b===d.length-1},even:function(a,b){return b%2===0},odd:function(a,b){return b%2===1},lt:function(a,b,c){return b<c[3]-0},gt:function(a,b,c){return b>c[3]-0},nth:function(a,b,c){return c[3]-0===b},eq:function(a,b,c){return c[3]-0===b}},filter:{PSEUDO:function(a,b,c,d){var e=b[1],f=o.filters[e];if(f)return f(a,c,b,d);else if(e==="contains")return(a.textContent||a.innerText||m.getText([a])||"").indexOf(b[3])>=0;else if(e==="not"){b=
b[3];c=0;for(d=b.length;c<d;c++)if(b[c]===a)return!1;return!0}else m.error(e)},CHILD:function(a,b){var c=b[1],d=a;switch(c){case "only":case "first":for(;d=d.previousSibling;)if(d.nodeType===1)return!1;if(c==="first")return!0;d=a;case "last":for(;d=d.nextSibling;)if(d.nodeType===1)return!1;return!0;case "nth":var c=b[2],e=b[3];if(c===1&&e===0)return!0;var f=b[0],g=a.parentNode;if(g&&(g.sizcache!==f||!a.nodeIndex)){for(var j=0,d=g.firstChild;d;d=d.nextSibling)if(d.nodeType===1)d.nodeIndex=++j;g.sizcache=
f}d=a.nodeIndex-e;return c===0?d===0:d%c===0&&d/c>=0}},ID:function(a,b){return a.nodeType===1&&a.getAttribute("id")===b},TAG:function(a,b){return b==="*"&&a.nodeType===1||a.nodeName.toLowerCase()===b},CLASS:function(a,b){return(" "+(a.className||a.getAttribute("class"))+" ").indexOf(b)>-1},ATTR:function(a,b){var c=b[1],c=o.attrHandle[c]?o.attrHandle[c](a):a[c]!=null?a[c]:a.getAttribute(c),d=c+"",e=b[2],f=b[4];return c==null?e==="!=":e==="="?d===f:e==="*="?d.indexOf(f)>=0:e==="~="?(" "+d+" ").indexOf(f)>=
0:!f?d&&c!==!1:e==="!="?d!==f:e==="^="?d.indexOf(f)===0:e==="$="?d.substr(d.length-f.length)===f:e==="|="?d===f||d.substr(0,f.length+1)===f+"-":!1},POS:function(a,b,c,d){var e=o.setFilters[b[2]];if(e)return e(a,c,b,d)}}},n=o.match.POS,t=function(a,b){return"\\"+(b-0+1)},s;for(s in o.match)o.match[s]=RegExp(o.match[s].source+/(?![^\[]*\])(?![^\(]*\))/.source),o.leftMatch[s]=RegExp(/(^(?:.|\r|\n)*?)/.source+o.match[s].source.replace(/\\(\d+)/g,t));var z=function(a,b){a=Array.prototype.slice.call(a,
0);if(b)return b.push.apply(b,a),b;return a};try{Array.prototype.slice.call(l.documentElement.childNodes,0)}catch(v){z=function(a,b){var c=0,d=b||[];if(f.call(a)==="[object Array]")Array.prototype.push.apply(d,a);else if(typeof a.length==="number")for(var e=a.length;c<e;c++)d.push(a[c]);else for(;a[c];c++)d.push(a[c]);return d}}var y,S;l.documentElement.compareDocumentPosition?y=function(a,b){if(a===b)return g=!0,0;if(!a.compareDocumentPosition||!b.compareDocumentPosition)return a.compareDocumentPosition?
-1:1;return a.compareDocumentPosition(b)&4?-1:1}:(y=function(a,b){var c,d,e=[],f=[];c=a.parentNode;d=b.parentNode;var j=c;if(a===b)return g=!0,0;else if(c===d)return S(a,b);else if(c){if(!d)return 1}else return-1;for(;j;)e.unshift(j),j=j.parentNode;for(j=d;j;)f.unshift(j),j=j.parentNode;c=e.length;d=f.length;for(j=0;j<c&&j<d;j++)if(e[j]!==f[j])return S(e[j],f[j]);return j===c?S(a,f[j],-1):S(e[j],b,1)},S=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});
m.getText=function(a){for(var b="",c,d=0;a[d];d++)c=a[d],c.nodeType===3||c.nodeType===4?b+=c.nodeValue:c.nodeType!==8&&(b+=m.getText(c.childNodes));return b};(function(){var a=l.createElement("div"),b="script"+(new Date).getTime(),c=l.documentElement;a.innerHTML="<a name='"+b+"'/>";c.insertBefore(a,c.firstChild);if(l.getElementById(b))o.find.ID=function(a,b,c){if(typeof b.getElementById!=="undefined"&&!c)return(b=b.getElementById(a[1]))?b.id===a[1]||typeof b.getAttributeNode!=="undefined"&&b.getAttributeNode("id").nodeValue===
a[1]?[b]:k:[]},o.filter.ID=function(a,b){var c=typeof a.getAttributeNode!=="undefined"&&a.getAttributeNode("id");return a.nodeType===1&&c&&c.nodeValue===b};c.removeChild(a);c=a=null})();(function(){var a=l.createElement("div");a.appendChild(l.createComment(""));if(a.getElementsByTagName("*").length>0)o.find.TAG=function(a,b){var c=b.getElementsByTagName(a[1]);if(a[1]==="*"){for(var d=[],e=0;c[e];e++)c[e].nodeType===1&&d.push(c[e]);c=d}return c};a.innerHTML="<a href='#'></a>";if(a.firstChild&&typeof a.firstChild.getAttribute!==
"undefined"&&a.firstChild.getAttribute("href")!=="#")o.attrHandle.href=function(a){return a.getAttribute("href",2)};a=null})();l.querySelectorAll&&function(){var a=m,b=l.createElement("div");b.innerHTML="<p class='TEST'></p>";if(!(b.querySelectorAll&&b.querySelectorAll(".TEST").length===0)){m=function(b,c,d,e){c=c||l;if(!e&&!m.isXML(c)){var f=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(b);if(f&&(c.nodeType===1||c.nodeType===9))if(f[1])return z(c.getElementsByTagName(b),d);else if(f[2]&&o.find.CLASS&&
c.getElementsByClassName)return z(c.getElementsByClassName(f[2]),d);if(c.nodeType===9){if(b==="body"&&c.body)return z([c.body],d);else if(f&&f[3]){var g=c.getElementById(f[3]);if(g&&g.parentNode){if(g.id===f[3])return z([g],d)}else return z([],d)}try{return z(c.querySelectorAll(b),d)}catch(j){}}else if(c.nodeType===1&&c.nodeName.toLowerCase()!=="object"){var f=c,h=(g=c.getAttribute("id"))||"__sizzle__",k=c.parentNode,p=/^\s*[+~]/.test(b);g?h=h.replace(/'/g,"\\$&"):c.setAttribute("id",h);if(p&&k)c=
c.parentNode;try{if(!p||k)return z(c.querySelectorAll("[id='"+h+"'] "+b),d)}catch(q){}finally{g||f.removeAttribute("id")}}}return a(b,c,d,e)};for(var c in a)m[c]=a[c];b=null}}();(function(){var a=l.documentElement,b=a.matchesSelector||a.mozMatchesSelector||a.webkitMatchesSelector||a.msMatchesSelector;if(b){var c=!b.call(l.createElement("div"),"div"),d=!1;try{b.call(l.documentElement,"[test!='']:sizzle")}catch(e){d=!0}m.matchesSelector=function(a,e){e=e.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!m.isXML(a))try{if(d||
!o.match.PSEUDO.test(e)&&!/!=/.test(e)){var f=b.call(a,e);if(f||!c||a.document&&a.document.nodeType!==11)return f}}catch(g){}return m(e,null,null,[a]).length>0}}})();(function(){var a=l.createElement("div");a.innerHTML="<div class='test e'></div><div class='test'></div>";if(a.getElementsByClassName&&a.getElementsByClassName("e").length!==0&&(a.lastChild.className="e",a.getElementsByClassName("e").length!==1))o.order.splice(1,0,"CLASS"),o.find.CLASS=function(a,b,c){if(typeof b.getElementsByClassName!==
"undefined"&&!c)return b.getElementsByClassName(a[1])},a=null})();m.contains=l.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):!0)}:l.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return!1};m.isXML=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?a.nodeName!=="HTML":!1};var w=function(a,b){for(var c,d=[],e="",f=b.nodeType?[b]:b;c=o.match.PSEUDO.exec(a);)e+=c[0],a=a.replace(o.match.PSEUDO,"");
a=o.relative[a]?a+"*":a;c=0;for(var g=f.length;c<g;c++)m(a,f[c],d);return m.filter(e,d)};c.find=m;c.expr=m.selectors;c.expr[":"]=c.expr.filters;c.unique=m.uniqueSort;c.text=m.getText;c.isXMLDoc=m.isXML;c.contains=m.contains})();var ub=/Until$/,vb=/^(?:parents|prevUntil|prevAll)/,wb=/,/,db=/^.[^:#\[\.,]*$/,xb=Array.prototype.slice,La=c.expr.match.POS,yb={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({find:function(a){var b=this,d,e;if(typeof a!=="string")return c(a).filter(function(){d=0;for(e=
b.length;d<e;d++)if(c.contains(b[d],this))return!0});var f=this.pushStack("","find",a),g,j,h;d=0;for(e=this.length;d<e;d++)if(g=f.length,c.find(a,this[d],f),d>0)for(j=g;j<f.length;j++)for(h=0;h<g;h++)if(f[h]===f[j]){f.splice(j--,1);break}return f},has:function(a){var b=c(a);return this.filter(function(){for(var a=0,e=b.length;a<e;a++)if(c.contains(this,b[a]))return!0})},not:function(a){return this.pushStack(ba(this,a,!1),"not",a)},filter:function(a){return this.pushStack(ba(this,a,!0),"filter",a)},
is:function(a){return!!a&&(typeof a==="string"?c.filter(a,this).length>0:this.filter(a).length>0)},closest:function(a,b){var d=[],e,f,g=this[0];if(c.isArray(a)){var j,h={},k=1;if(g&&a.length){e=0;for(f=a.length;e<f;e++)j=a[e],h[j]||(h[j]=La.test(j)?c(j,b||this.context):j);for(;g&&g.ownerDocument&&g!==b;){for(j in h)e=h[j],(e.jquery?e.index(g)>-1:c(g).is(e))&&d.push({selector:j,elem:g,level:k});g=g.parentNode;k++}}return d}j=La.test(a)||typeof a!=="string"?c(a,b||this.context):0;e=0;for(f=this.length;e<
f;e++)for(g=this[e];g;)if(j?j.index(g)>-1:c.find.matchesSelector(g,a)){d.push(g);break}else if(g=g.parentNode,!g||!g.ownerDocument||g===b||g.nodeType===11)break;d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){var d=typeof a==="string"?c(a,b):c.makeArray(a&&a.nodeType?[a]:a),e=c.merge(this.get(),d);return this.pushStack(!d[0]||
!d[0].parentNode||d[0].parentNode.nodeType===11||!e[0]||!e[0].parentNode||e[0].parentNode.nodeType===11?e:c.unique(e))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},
prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d),g=xb.call(arguments);ub.test(a)||
(e=d);e&&typeof e==="string"&&(f=c.filter(e,f));f=this.length>1&&!yb[a]?c.unique(f):f;if((this.length>1||wb.test(e))&&vb.test(a))f=f.reverse();return this.pushStack(f,a,g.join(","))}});c.extend({filter:function(a,b,d){d&&(a=":not("+a+")");return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){for(var e=[],a=a[b];a&&a.nodeType!==9&&(d===k||a.nodeType!==1||!c(a).is(d));)a.nodeType===1&&e.push(a),a=a[b];return e},nth:function(a,b,c){for(var b=b||1,e=0;a;a=
a[c])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&c.push(a);return c}});var zb=/ jQuery\d+="(?:\d+|null)"/g,ta=/^\s+/,Ma=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,Na=/<([\w:]+)/,Ab=/<tbody/i,Bb=/<|&#?\w+;/,Oa=/<(?:script|object|embed|option|style)/i,Pa=/checked\s*(?:[^=]|=\s*.checked.)/i,Cb=/\/(java|ecma)script/i,C={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>",
"</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};C.optgroup=C.option;C.tbody=C.tfoot=C.colgroup=C.caption=C.thead;C.th=C.td;if(!c.support.htmlSerialize)C._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,
b,d.text()))});if(typeof a!=="object"&&a!==k)return this.empty().append((this[0]&&this[0].ownerDocument||l).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapAll(a.call(this,b))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&a.firstChild.nodeType===1;)a=a.firstChild;return a}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,
b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,!0,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,!0,function(a){this.nodeType===1&&this.insertBefore(a,
this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,
c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length)!b&&e.nodeType===1&&(c.cleanData(e.getElementsByTagName("*")),c.cleanData([e])),e.parentNode&&e.parentNode.removeChild(e);return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a,b){a=a==null?!1:a;b=b==null?a:b;return this.map(function(){return c.clone(this,
a,b)})},html:function(a){if(a===k)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(zb,""):null;else if(typeof a==="string"&&!Oa.test(a)&&(c.support.leadingWhitespace||!ta.test(a))&&!C[(Na.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ma,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1)c.cleanData(this[b].getElementsByTagName("*")),this[b].innerHTML=a}catch(e){this.empty().append(a)}}else c.isFunction(a)?this.each(function(b){var d=c(this);d.html(a.call(this,
b,d.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),e=d.html();d.replaceWith(a.call(this,b,e))});typeof a!=="string"&&(a=c(a).detach());return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.length?this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a):this},detach:function(a){return this.remove(a,!0)},
domManip:function(a,b,d){var e,f,g,j=a[0],h=[];if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&Pa.test(j))return this.each(function(){c(this).domManip(a,b,d,!0)});if(c.isFunction(j))return this.each(function(e){var f=c(this);a[0]=j.call(this,e,b?f.html():k);f.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,h);g=e.fragment;if(f=g.childNodes.length===1?g=g.firstChild:
g.firstChild){b=b&&c.nodeName(f,"tr");f=0;for(var p=this.length,m=p-1;f<p;f++)d.call(b?c.nodeName(this[f],"table")?this[f].getElementsByTagName("tbody")[0]||this[f].appendChild(this[f].ownerDocument.createElement("tbody")):this[f]:this[f],e.cacheable||p>1&&f<m?c.clone(g,!0,!0):g)}h.length&&c.each(h,eb)}return this}});c.buildFragment=function(a,b,d){var e,f,g,b=b&&b[0]?b[0].ownerDocument||b[0]:l;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===l&&a[0].charAt(0)==="<"&&!Oa.test(a[0])&&
(c.support.checkClone||!Pa.test(a[0])))f=!0,(g=c.fragments[a[0]])&&g!==1&&(e=g);e||(e=b.createDocumentFragment(),c.clean(a,b,e,d));f&&(c.fragments[a[0]]=g?e:1);return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e=[],d=c(d),f=this.length===1&&this[0].parentNode;if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1)return d[b](this[0]),this;else{for(var f=
0,g=d.length;f<g;f++){var j=(f>0?this.clone(!0):this).get();c(d[f])[b](j);e=e.concat(j)}return this.pushStack(e,a,d.selector)}}});c.extend({clone:function(a,b,d){var e=a.cloneNode(!0),f,g,j;if((!c.support.noCloneEvent||!c.support.noCloneChecked)&&(a.nodeType===1||a.nodeType===11)&&!c.isXMLDoc(a)){X(a,e);f=A(a);g=A(e);for(j=0;f[j];++j)X(f[j],g[j])}if(b&&(H(a,e),d)){f=A(a);g=A(e);for(j=0;f[j];++j)H(f[j],g[j])}return e},clean:function(a,b,d,e){b=b||l;typeof b.createElement==="undefined"&&(b=b.ownerDocument||
b[0]&&b[0].ownerDocument||l);for(var f=[],g=0,j;(j=a[g])!=null;g++)if(typeof j==="number"&&(j+=""),j){if(typeof j==="string")if(Bb.test(j)){j=j.replace(Ma,"<$1></$2>");var h=(Na.exec(j)||["",""])[1].toLowerCase(),k=C[h]||C._default,m=k[0],o=b.createElement("div");for(o.innerHTML=k[1]+j+k[2];m--;)o=o.lastChild;if(!c.support.tbody){m=Ab.test(j);h=h==="table"&&!m?o.firstChild&&o.firstChild.childNodes:k[1]==="<table>"&&!m?o.childNodes:[];for(k=h.length-1;k>=0;--k)c.nodeName(h[k],"tbody")&&!h[k].childNodes.length&&
h[k].parentNode.removeChild(h[k])}!c.support.leadingWhitespace&&ta.test(j)&&o.insertBefore(b.createTextNode(ta.exec(j)[0]),o.firstChild);j=o.childNodes}else j=b.createTextNode(j);var n;if(!c.support.appendChecked)if(j[0]&&typeof(n=j.length)==="number")for(g=0;g<n;g++)I(j[g]);else I(j);j.nodeType?f.push(j):f=c.merge(f,j)}if(d){a=function(a){return!a.type||Cb.test(a.type)};for(g=0;f[g];g++)e&&c.nodeName(f[g],"script")&&(!f[g].type||f[g].type.toLowerCase()==="text/javascript")?e.push(f[g].parentNode?
f[g].parentNode.removeChild(f[g]):f[g]):(f[g].nodeType===1&&(b=c.grep(f[g].getElementsByTagName("script"),a),f.splice.apply(f,[g+1,0].concat(b))),d.appendChild(f[g]))}return f},cleanData:function(a){for(var b,d,e=c.cache,f=c.expando,g=c.event.special,j=c.support.deleteExpando,h=0,k;(k=a[h])!=null;h++)if(!k.nodeName||!c.noData[k.nodeName.toLowerCase()])if(d=k[c.expando]){if((b=e[d]&&e[d][f])&&b.events){for(var m in b.events)g[m]?c.event.remove(k,m):c.removeEvent(k,m,b.handle);if(b.handle)b.handle.elem=
null}j?delete k[c.expando]:k.removeAttribute&&k.removeAttribute(c.expando);delete e[d]}}});var Qa=/alpha\([^)]*\)/i,Db=/opacity=([^)]*)/,Eb=/-([a-z])/ig,Fb=/([A-Z]|^ms)/g,Ra=/^-?\d+(?:px)?$/i,Gb=/^-?\d/,Hb=/^[+\-]=/,Ib=/[^+\-\.\de]+/g,Jb={position:"absolute",visibility:"hidden",display:"block"},fb=["Left","Right"],gb=["Top","Bottom"],P,Sa,fa,Kb=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){if(arguments.length===2&&b===k)return this;return c.access(this,a,b,!0,function(a,b,f){return f!==
k?c.style(a,b,f):c.css(a,b)})};c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=P(a,"opacity","opacity");return c===""?"1":c}else return a.style.opacity}}},cssNumber:{zIndex:!0,fontWeight:!0,opacity:!0,zoom:!0,lineHeight:!0,widows:!0,orphans:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(a&&!(a.nodeType===3||a.nodeType===8||!a.style)){var f,g=c.camelCase(b),j=a.style,h=c.cssHooks[g],b=c.cssProps[g]||g;if(d!==k){if(e=typeof d,!(e==="number"&&
isNaN(d)||d==null))if(e==="string"&&Hb.test(d)&&(d=+d.replace(Ib,"")+parseFloat(c.css(a,b))),e==="number"&&!c.cssNumber[g]&&(d+="px"),!h||!("set"in h)||(d=h.set(a,d))!==k)try{j[b]=d}catch(l){}}else{if(h&&"get"in h&&(f=h.get(a,!1,e))!==k)return f;return j[b]}}},css:function(a,b,d){var e,f,b=c.camelCase(b);f=c.cssHooks[b];b=c.cssProps[b]||b;b==="cssFloat"&&(b="float");if(f&&"get"in f&&(e=f.get(a,!0,d))!==k)return e;else if(P)return P(a,b)},swap:function(a,b,c){var e={},f;for(f in b)e[f]=a.style[f],
a.style[f]=b[f];c.call(a);for(f in b)a.style[f]=e[f]},camelCase:function(a){return a.replace(Eb,Kb)}});c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,e,f){var g;if(e){a.offsetWidth!==0?g=wa(a,b,f):c.swap(a,Jb,function(){g=wa(a,b,f)});if(g<=0&&(g=P(a,b,b),g==="0px"&&fa&&(g=fa(a,b,b)),g!=null))return g===""||g==="auto"?"0px":g;if(g<0||g==null)return g=a.style[b],g===""||g==="auto"?"0px":g;return typeof g==="string"?g:g+"px"}},set:function(a,b){if(Ra.test(b)){if(b=
parseFloat(b),b>=0)return b+"px"}else return b}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return Db.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){var d=a.style,e=a.currentStyle;d.zoom=1;var f=c.isNaN(b)?"":"alpha(opacity="+b*100+")",e=e&&e.filter||d.filter||"";d.filter=Qa.test(e)?e.replace(Qa,f):e+" "+f}};c(function(){if(!c.support.reliableMarginRight)c.cssHooks.marginRight={get:function(a,b){var d;
c.swap(a,{display:"inline-block"},function(){d=b?P(a,"margin-right","marginRight"):a.style.marginRight});return d}}});l.defaultView&&l.defaultView.getComputedStyle&&(Sa=function(a,b){var d,e,b=b.replace(Fb,"-$1").toLowerCase();if(!(e=a.ownerDocument.defaultView))return k;if(e=e.getComputedStyle(a,null))d=e.getPropertyValue(b),d===""&&!c.contains(a.ownerDocument.documentElement,a)&&(d=c.style(a,b));return d});l.documentElement.currentStyle&&(fa=function(a,b){var c,e=a.currentStyle&&a.currentStyle[b],
f=a.runtimeStyle&&a.runtimeStyle[b],g=a.style;if(!Ra.test(e)&&Gb.test(e)){c=g.left;if(f)a.runtimeStyle.left=a.currentStyle.left;g.left=b==="fontSize"?"1em":e||0;e=g.pixelLeft+"px";g.left=c;if(f)a.runtimeStyle.left=f}return e===""?"auto":e});P=Sa||fa;if(c.expr&&c.expr.filters)c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style.display||c.css(a,"display"))==="none"},c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)};
var Lb=/%20/g,hb=/\[\]$/,Ta=/\r?\n/g,Mb=/#.*$/,Nb=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,Ob=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,Pb=/^(?:GET|HEAD)$/,Qb=/^\/\//,Ua=/\?/,Rb=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,Sb=/^(?:select|textarea)/i,ya=/\s+/,Tb=/([?&])_=[^&]*/,Va=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?)?/,Wa=c.fn.load,ia={},Xa={},N,L;try{N=kb.href}catch(Zb){N=l.createElement("a"),N.href="",N=N.href}L=Va.exec(N.toLowerCase())||
[];c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&Wa)return Wa.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0)var f=a.slice(e,a.length),a=a.slice(0,e);e="GET";b&&(c.isFunction(b)?(d=b,b=k):typeof b==="object"&&(b=c.param(b,c.ajaxSettings.traditional),e="POST"));var g=this;c.ajax({url:a,type:e,dataType:"html",data:b,complete:function(a,b,e){e=a.responseText;a.isResolved()&&(a.done(function(a){e=a}),g.html(f?c("<div>").append(e.replace(Rb,"")).find(f):
e));d&&g.each(d,[e,b,a])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||Sb.test(this.nodeName)||Ob.test(this.type))}).map(function(a,b){var d=c(this).val();return d==null?null:c.isArray(d)?c.map(d,function(a){return{name:b.name,value:a.replace(Ta,"\r\n")}}):{name:b.name,value:d.replace(Ta,"\r\n")}}).get()}});
c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(a){return this.bind(b,a)}});c.each(["get","post"],function(a,b){c[b]=function(a,e,f,g){c.isFunction(e)&&(g=g||f,f=e,e=k);return c.ajax({type:b,url:a,data:e,success:f,dataType:g})}});c.extend({getScript:function(a,b){return c.get(a,k,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},ajaxSetup:function(a,b){b?c.extend(!0,a,c.ajaxSettings,b):(b=a,a=c.extend(!0,c.ajaxSettings,
b));for(var d in{context:1,url:1})d in b?a[d]=b[d]:d in c.ajaxSettings&&(a[d]=c.ajaxSettings[d]);return a},ajaxSettings:{url:N,isLocal:/^(?:about|app|app\-storage|.+\-extension|file|widget):$/.test(L[1]),global:!0,type:"GET",contentType:"application/x-www-form-urlencoded",processData:!0,async:!0,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":"*/*"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",
text:"responseText"},converters:{"* text":h.String,"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML}},ajaxPrefilter:xa(ia),ajaxTransport:xa(Xa),ajax:function(a,b){function d(a,b,d,o){if(w!==2){w=2;y&&clearTimeout(y);z=k;t=o||"";r.readyState=a?4:0;var n,s,u;if(d){var o=e,v=r,x=o.contents,A=o.dataTypes,D=o.responseFields,E,B,O,H;for(B in D)B in d&&(v[D[B]]=d[B]);for(;A[0]==="*";)A.shift(),E===k&&(E=o.mimeType||v.getResponseHeader("content-type"));if(E)for(B in x)if(x[B]&&x[B].test(E)){A.unshift(B);
break}if(A[0]in d)O=A[0];else{for(B in d){if(!A[0]||o.converters[B+" "+A[0]]){O=B;break}H||(H=B)}O=O||H}O?(O!==A[0]&&A.unshift(O),d=d[O]):d=void 0}else d=k;if(a>=200&&a<300||a===304){if(e.ifModified){if(E=r.getResponseHeader("Last-Modified"))c.lastModified[m]=E;if(E=r.getResponseHeader("Etag"))c.etag[m]=E}if(a===304)b="notmodified",n=!0;else try{E=e;E.dataFilter&&(d=E.dataFilter(d,E.dataType));var I=E.dataTypes;B={};var F,K,N=I.length,L,Q=I[0],G,M,R,T,J;for(F=1;F<N;F++){if(F===1)for(K in E.converters)typeof K===
"string"&&(B[K.toLowerCase()]=E.converters[K]);G=Q;Q=I[F];if(Q==="*")Q=G;else if(G!=="*"&&G!==Q){M=G+" "+Q;R=B[M]||B["* "+Q];if(!R)for(T in J=k,B)if(L=T.split(" "),L[0]===G||L[0]==="*")if(J=B[L[1]+" "+Q]){T=B[T];T===!0?R=J:J===!0&&(R=T);break}!R&&!J&&c.error("No conversion from "+M.replace(" "," to "));R!==!0&&(d=R?R(d):J(T(d)))}}s=d;b="success";n=!0}catch(P){b="parsererror",u=P}}else if(u=b,!b||a)b="error",a<0&&(a=0);r.status=a;r.statusText=b;n?j.resolveWith(f,[s,b,r]):j.rejectWith(f,[r,b,u]);r.statusCode(l);
l=k;C&&g.trigger("ajax"+(n?"Success":"Error"),[r,e,n?s:u]);h.resolveWith(f,[r,b]);C&&(g.trigger("ajaxComplete",[r,e]),--c.active||c.event.trigger("ajaxStop"))}}typeof a==="object"&&(b=a,a=k);var b=b||{},e=c.ajaxSetup({},b),f=e.context||e,g=f!==e&&(f.nodeType||f instanceof c)?c(f):c.event,j=c.Deferred(),h=c._Deferred(),l=e.statusCode||{},m,o={},n={},t,s,z,y,v,w=0,C,u,r={readyState:0,setRequestHeader:function(a,b){if(!w){var c=a.toLowerCase(),a=n[c]=n[c]||a;o[a]=b}return this},getAllResponseHeaders:function(){return w===
2?t:null},getResponseHeader:function(a){var b;if(w===2){if(!s)for(s={};b=Nb.exec(t);)s[b[1].toLowerCase()]=b[2];b=s[a.toLowerCase()]}return b===k?null:b},overrideMimeType:function(a){if(!w)e.mimeType=a;return this},abort:function(a){a=a||"abort";z&&z.abort(a);d(0,a);return this}};j.promise(r);r.success=r.done;r.error=r.fail;r.complete=h.done;r.statusCode=function(a){if(a){var b;if(w<2)for(b in a)l[b]=[l[b],a[b]];else b=a[r.status],r.then(b,b)}return this};e.url=((a||e.url)+"").replace(Mb,"").replace(Qb,
L[1]+"//");e.dataTypes=c.trim(e.dataType||"*").toLowerCase().split(ya);if(e.crossDomain==null)v=Va.exec(e.url.toLowerCase()),e.crossDomain=!(!v||!(v[1]!=L[1]||v[2]!=L[2]||(v[3]||(v[1]==="http:"?80:443))!=(L[3]||(L[1]==="http:"?80:443))));if(e.data&&e.processData&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);ca(ia,e,b,r);if(w===2)return!1;C=e.global;e.type=e.type.toUpperCase();e.hasContent=!Pb.test(e.type);C&&c.active++===0&&c.event.trigger("ajaxStart");if(!e.hasContent&&(e.data&&
(e.url+=(Ua.test(e.url)?"&":"?")+e.data),m=e.url,e.cache===!1)){v=c.now();var A=e.url.replace(Tb,"$1_="+v);e.url=A+(A===e.url?(Ua.test(e.url)?"&":"?")+"_="+v:"")}(e.data&&e.hasContent&&e.contentType!==!1||b.contentType)&&r.setRequestHeader("Content-Type",e.contentType);e.ifModified&&(m=m||e.url,c.lastModified[m]&&r.setRequestHeader("If-Modified-Since",c.lastModified[m]),c.etag[m]&&r.setRequestHeader("If-None-Match",c.etag[m]));r.setRequestHeader("Accept",e.dataTypes[0]&&e.accepts[e.dataTypes[0]]?
e.accepts[e.dataTypes[0]]+(e.dataTypes[0]!=="*"?", */*; q=0.01":""):e.accepts["*"]);for(u in e.headers)r.setRequestHeader(u,e.headers[u]);if(e.beforeSend&&(e.beforeSend.call(f,r,e)===!1||w===2))return r.abort(),!1;for(u in{success:1,error:1,complete:1})r[u](e[u]);if(z=ca(Xa,e,b,r)){r.readyState=1;C&&g.trigger("ajaxSend",[r,e]);e.async&&e.timeout>0&&(y=setTimeout(function(){r.abort("timeout")},e.timeout));try{w=1,z.send(o,d)}catch(D){status<2?d(-1,D):c.error(D)}}else d(-1,"No Transport");return r},
param:function(a,b){var d=[],e=function(a,b){b=c.isFunction(b)?b():b;d[d.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};if(b===k)b=c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){e(this.name,this.value)});else for(var f in a)ja(f,a[f],b,e);return d.join("&").replace(Lb,"+")}});c.extend({active:0,lastModified:{},etag:{}});var Ub=c.now(),ga=/(\=)\?(&|$)|\?\?/i;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){return c.expando+"_"+Ub++}});
c.ajaxPrefilter("json jsonp",function(a,b,d){b=a.contentType==="application/x-www-form-urlencoded"&&typeof a.data==="string";if(a.dataTypes[0]==="jsonp"||a.jsonp!==!1&&(ga.test(a.url)||b&&ga.test(a.data))){var e,f=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,g=h[f],j=a.url,k=a.data,l="$1"+f+"$2";a.jsonp!==!1&&(j=j.replace(ga,l),a.url===j&&(b&&(k=k.replace(ga,l)),a.data===k&&(j+=(/\?/.test(j)?"&":"?")+a.jsonp+"="+f)));a.url=j;a.data=k;h[f]=function(a){e=[a]};d.always(function(){h[f]=
g;if(e&&c.isFunction(g))h[f](e[0])});a.converters["script json"]=function(){e||c.error(f+" was not called");return e[0]};a.dataTypes[0]="json";return"script"}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/javascript|ecmascript/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){if(a.cache===k)a.cache=!1;if(a.crossDomain)a.type="GET",a.global=!1});c.ajaxTransport("script",
function(a){if(a.crossDomain){var b,c=l.head||l.getElementsByTagName("head")[0]||l.documentElement;return{send:function(e,f){b=l.createElement("script");b.async="async";if(a.scriptCharset)b.charset=a.scriptCharset;b.src=a.url;b.onload=b.onreadystatechange=function(a,e){if(e||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,c&&b.parentNode&&c.removeChild(b),b=k,e||f(200,"success")};c.insertBefore(b,c.firstChild)},abort:function(){if(b)b.onload(0,1)}}}});var ua=
h.ActiveXObject?function(){for(var a in U)U[a](0,1)}:!1,Vb=0,U;c.ajaxSettings.xhr=h.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&za()))a:{try{a=new h.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:za;(function(a){c.extend(c.support,{ajax:!!a,cors:!!a&&"withCredentials"in a})})(c.ajaxSettings.xhr());c.support.ajax&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,e){var f=a.xhr(),g,j;a.username?f.open(a.type,a.url,a.async,
a.username,a.password):f.open(a.type,a.url,a.async);if(a.xhrFields)for(j in a.xhrFields)f[j]=a.xhrFields[j];a.mimeType&&f.overrideMimeType&&f.overrideMimeType(a.mimeType);!a.crossDomain&&!d["X-Requested-With"]&&(d["X-Requested-With"]="XMLHttpRequest");try{for(j in d)f.setRequestHeader(j,d[j])}catch(l){}f.send(a.hasContent&&a.data||null);b=function(d,j){var h,l,n,q,t;try{if(b&&(j||f.readyState===4)){b=k;if(g)f.onreadystatechange=c.noop,ua&&delete U[g];if(j)f.readyState!==4&&f.abort();else{h=f.status;
n=f.getAllResponseHeaders();q={};if((t=f.responseXML)&&t.documentElement)q.xml=t;q.text=f.responseText;try{l=f.statusText}catch(v){l=""}!h&&a.isLocal&&!a.crossDomain?h=q.text?200:404:h===1223&&(h=204)}}}catch(y){j||e(-1,y)}q&&e(h,l,q,n)};!a.async||f.readyState===4?b():(g=++Vb,ua&&(U||(U={},c(h).unload(ua)),U[g]=b),f.onreadystatechange=b)},abort:function(){b&&b(0,1)}}}});var ka={},D,Y,Wb=/^(?:toggle|show|hide)$/,Xb=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i,V,Ba=[["height","marginTop","marginBottom","paddingTop",
"paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]],da,va=h.webkitRequestAnimationFrame||h.mozRequestAnimationFrame||h.oRequestAnimationFrame;c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate(M("show",3),a,b,d);else{for(var d=0,e=this.length;d<e;d++)if(a=this[d],a.style){b=a.style.display;if(!c._data(a,"olddisplay")&&b==="none")b=a.style.display="";b===""&&c.css(a,"display")==="none"&&c._data(a,"olddisplay",Ca(a.nodeName))}for(d=0;d<e;d++)if(a=
this[d],a.style&&(b=a.style.display,b===""||b==="none"))a.style.display=c._data(a,"olddisplay")||"";return this}},hide:function(a,b,d){if(a||a===0)return this.animate(M("hide",3),a,b,d);else{a=0;for(b=this.length;a<b;a++)this[a].style&&(d=c.css(this[a],"display"),d!=="none"&&!c._data(this[a],"olddisplay")&&c._data(this[a],"olddisplay",d));for(a=0;a<b;a++)if(this[a].style)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";c.isFunction(a)&&
c.isFunction(b)?this._toggle.apply(this,arguments):a==null||e?this.each(function(){var b=e?a:c(this).is(":hidden");c(this)[b?"show":"hide"]()}):this.animate(M("toggle",3),a,b,d);return this},fadeTo:function(a,b,c,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(f.complete,[!1]);return this[f.queue===!1?"each":"queue"](function(){f.queue===!1&&c._mark(this);var b=c.extend({},
f),d=this.nodeType===1,e=d&&c(this).is(":hidden"),h,k,l,n,t,s;b.animatedProperties={};for(l in a){h=c.camelCase(l);l!==h&&(a[h]=a[l],delete a[l]);k=a[h];if(k==="hide"&&e||k==="show"&&!e)return b.complete.call(this);if(d&&(h==="height"||h==="width"))if(b.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY],c.css(this,"display")==="inline"&&c.css(this,"float")==="none")c.support.inlineBlockNeedsLayout?(n=Ca(this.nodeName),n==="inline"?this.style.display="inline-block":(this.style.display=
"inline",this.style.zoom=1)):this.style.display="inline-block";b.animatedProperties[h]=c.isArray(k)?k[1]:b.specialEasing&&b.specialEasing[h]||b.easing||"swing"}if(b.overflow!=null)this.style.overflow="hidden";for(l in a)if(d=new c.fx(this,b,l),k=a[l],Wb.test(k))d[k==="toggle"?e?"show":"hide":k]();else n=Xb.exec(k),t=d.cur(),n?(k=parseFloat(n[2]),s=n[3]||(c.cssNumber[h]?"":"px"),s!=="px"&&(c.style(this,l,(k||1)+s),t*=(k||1)/d.cur(),c.style(this,l,t+s)),n[1]&&(k=(n[1]==="-="?-1:1)*k+t),d.custom(t,k,
s)):d.custom(t,k,"");return!0})},stop:function(a,b){a&&this.queue([]);this.each(function(){var a=c.timers,e=a.length;for(b||c._unmark(!0,this);e--;)if(a[e].elem===this){if(b)a[e](!0);a.splice(e,1)}});b||this.dequeue();return this}});c.each({slideDown:M("show",1),slideUp:M("hide",1),slideToggle:M("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,c,f){return this.animate(b,a,c,f)}});c.extend({speed:function(a,b,d){var e=a&&typeof a===
"object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(a){e.queue!==!1?c.dequeue(this):a!==!1&&c._unmark(this);c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,c,e){return c+e*a},swing:function(a,b,c,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+c}},timers:[],
fx:function(a,b,c){this.options=b;this.elem=a;this.prop=c;b.orig=b.orig||{}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a,b=c.css(this.elem,this.prop);return isNaN(a=parseFloat(b))?!b||b==="auto"?0:b:a},custom:function(a,b,d){function e(a){return f.step(a)}var f=
this,g=c.fx,j;this.startTime=da||Aa();this.start=a;this.end=b;this.unit=d||this.unit||(c.cssNumber[this.prop]?"":"px");this.now=this.start;this.pos=this.state=0;e.elem=this.elem;e()&&c.timers.push(e)&&!V&&(va?(V=1,j=function(){V&&(va(j),g.tick())},va(j)):V=setInterval(g.tick,g.interval))},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=!0;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=
c.style(this.elem,this.prop);this.options.hide=!0;this.custom(this.cur(),0)},step:function(a){var b=da||Aa(),d=!0,e=this.elem,f=this.options,g;if(a||b>=f.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();f.animatedProperties[this.prop]=!0;for(g in f.animatedProperties)f.animatedProperties[g]!==!0&&(d=!1);if(d){f.overflow!=null&&!c.support.shrinkWrapBlocks&&c.each(["","X","Y"],function(a,b){e.style["overflow"+b]=f.overflow[a]});f.hide&&c(e).hide();if(f.hide||f.show)for(var j in f.animatedProperties)c.style(e,
j,f.orig[j]);f.complete.call(e)}return!1}else f.duration==Infinity?this.now=b:(a=b-this.startTime,this.state=a/f.duration,this.pos=c.easing[f.animatedProperties[this.prop]](this.state,a,0,1,f.duration),this.now=this.start+(this.end-this.start)*this.pos),this.update();return!0}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=a.length;b--;)a[b]()||a.splice(b,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(V);V=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,
"opacity",a.now)},_default:function(a){a.elem.style&&a.elem.style[a.prop]!=null?a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit:a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var Yb=/^t(?:able|d|h)$/i,Ya=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in l.documentElement?function(a){var b=this[0],d;if(a)return this.each(function(b){c.offset.setOffset(this,
a,b)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var f=b.ownerDocument,g=f.documentElement;if(!d||!c.contains(g,b))return d?{top:d.top,left:d.left}:{top:0,left:0};b=f.body;f=la(f);return{top:d.top+(f.pageYOffset||c.support.boxModel&&g.scrollTop||b.scrollTop)-(g.clientTop||b.clientTop||0),left:d.left+(f.pageXOffset||c.support.boxModel&&g.scrollLeft||b.scrollLeft)-(g.clientLeft||b.clientLeft||0)}}:function(a){var b=
this[0];if(a)return this.each(function(b){c.offset.setOffset(this,a,b)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d,e=b.offsetParent,f=b.ownerDocument,g=f.documentElement,j=f.body;d=(f=f.defaultView)?f.getComputedStyle(b,null):b.currentStyle;for(var h=b.offsetTop,k=b.offsetLeft;(b=b.parentNode)&&b!==j&&b!==g;){if(c.offset.supportsFixedPosition&&d.position==="fixed")break;d=f?f.getComputedStyle(b,null):b.currentStyle;h-=
b.scrollTop;k-=b.scrollLeft;if(b===e){h+=b.offsetTop;k+=b.offsetLeft;if(c.offset.doesNotAddBorder&&(!c.offset.doesAddBorderForTableAndCells||!Yb.test(b.nodeName)))h+=parseFloat(d.borderTopWidth)||0,k+=parseFloat(d.borderLeftWidth)||0;e=b.offsetParent}c.offset.subtractsBorderForOverflowNotVisible&&d.overflow!=="visible"&&(h+=parseFloat(d.borderTopWidth)||0,k+=parseFloat(d.borderLeftWidth)||0)}if(d.position==="relative"||d.position==="static")h+=j.offsetTop,k+=j.offsetLeft;c.offset.supportsFixedPosition&&
d.position==="fixed"&&(h+=Math.max(g.scrollTop,j.scrollTop),k+=Math.max(g.scrollLeft,j.scrollLeft));return{top:h,left:k}};c.offset={initialize:function(){var a=l.body,b=l.createElement("div"),d,e,f,g=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;f=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=e.offsetTop!==5;this.doesAddBorderForTableAndCells=f.offsetTop===5;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=e.offsetTop===20||e.offsetTop===15;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=e.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==g;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();c.offset.doesNotIncludeMarginInBodyOffset&&(b+=parseFloat(c.css(a,"marginTop"))||0,d+=parseFloat(c.css(a,"marginLeft"))||0);return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),g=f.offset(),j=c.css(a,"top"),h=c.css(a,"left"),k={},l={};(e==="absolute"||e==="fixed")&&c.inArray("auto",[j,h])>-1?(l=f.position(),e=l.top,h=
l.left):(e=parseFloat(j)||0,h=parseFloat(h)||0);c.isFunction(b)&&(b=b.call(a,d,g));if(b.top!=null)k.top=b.top-g.top+e;if(b.left!=null)k.left=b.left-g.left+h;"using"in b?b.using.call(a,k):f.css(k)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=Ya.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=
parseFloat(c.css(b[0],"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||l.body;a&&!Ya.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(b){var f,g;if(b===k){f=this[0];if(!f)return null;return(g=la(f))?"pageXOffset"in g?g[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&g.document.documentElement[d]||
g.document.body[d]:f[d]}return this.each(function(){(g=la(this))?g.scrollTo(!a?b:c(g).scrollLeft(),a?b:c(g).scrollTop()):this[d]=b})}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(a){return this[0]?parseFloat(c.css(this[0],d,a?"margin":"border")):null};c.fn[d]=function(a){var f=this[0];if(!f)return a==null?null:this;if(c.isFunction(a))return this.each(function(b){var f=
c(this);f[d](a.call(this,b,f[d]()))});if(c.isWindow(f)){var g=f.document.documentElement["client"+b];return f.document.compatMode==="CSS1Compat"&&g||f.document.body["client"+b]||g}else return f.nodeType===9?Math.max(f.documentElement["client"+b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]):a===k?(f=c.css(f,d),g=parseFloat(f),c.isNaN(g)?f:g):this.css(d,typeof a==="string"?a:a+"px")}});h.jQuery=h.$=c})(window);
(function(h){function k(k){function y(){k?G.removeData(k):A&&delete n[A]}function F(){w.id=setTimeout(function(){w.fn()},K)}var W=this,G,w={},ba=k?h.fn:h,H=arguments,X=4,A=H[1],K=H[2],I=H[3];typeof A!=="string"&&(X--,A=k=0,K=H[1],I=H[2]);k?(G=W.eq(0),G.data(k,w=G.data(k)||{})):A&&(w=n[A]||(n[A]={}));w.id&&clearTimeout(w.id);delete w.id;if(I)w.fn=function(h){typeof I==="string"&&(I=ba[I]);I.apply(W,v.call(H,X))===!0&&!h?F():y()},F();else if(w.fn)return K===void 0?y():w.fn(K===!1),!0;else y()}var n=
{},v=Array.prototype.slice;h.doTimeout=function(){return k.apply(window,[0].concat(v.call(arguments)))};h.fn.doTimeout=function(){var h=v.call(arguments),n=k.apply(this,["doTimeout"+h[0]].concat(h));return typeof h[0]==="number"||typeof h[1]==="number"?this:n}})(jQuery);function detectLocalStorageSupport(){try{return!!localStorage.getItem}catch(h){return!1}}function pLocal(h,k){if(detectLocalStorageSupport())if(k==null)return localStorage[h];else localStorage[h]=k;else return!1}
function pLocalDelete(h){if(detectLocalStorageSupport())localStorage.removeItem(h);else return!1}function pcID(h){regexp=/([^:\/]+):([^:\/]+):([^\/]+)\/?$/;h=regexp.exec(h.attr("action"));return h[1]+h[2]+h[3]}
function pcSave(h){var k=h.parent(),n=k.attr("action"),v=k.attr("method");$.ajax({type:v,url:n,data:k.serialize(),beforeSend:function(){h.attr("disabled",!0);k.css({opacity:0.3});pLocal(pcID(k),k.find("textarea").val())},success:function(n){n.length==0?(h.attr("disabled",!1),k.css({opacity:1})):(pcResponse=$(n).nodetype(1).hide(),pcResponse.find("> fieldset").length==0&&pLocalDelete(pcID(k)),k.slideUp(500,function(){k.replaceWith(pcResponse);pcResponse.slideDown(500)}))},error:function(){k.find("p.error").length==
0&&k.prepend('<p class="error">There was a problem sending your comment. Please try again later.</p>');h.attr("disabled",!1);k.css({opacity:1})},dataType:"html"})}
function pdLoad(h){var k=h.attr("href");pdDiscussion=h.closest("article").find("section.comments");pdDiscussion.length==0?$.ajax({type:"GET",url:k,beforeSend:function(){pdOrigLinkHTML=h.html();h.html("Loading...")},success:function(k){commentBlock=typeof innerShiv=="function"?$(innerShiv(k,!1)):$(k);commentBlock.children("section.comments").appendTo(h.closest("article")).hide().show(500).find("> article").paxNew();h.html(pdOrigLinkHTML);h.closest("article").paxPreFill()},dataType:"html"}):pdDiscussion.hide(500,
function(){pdDiscussion.remove()})}function paxPreFill(h){h=h.find("> .comments > form");if(h.length==0)return!1;var k=pLocal(pcID(h)),n=getPaxUserCookie();h.find('input[name="name"]').attr("value",n[0]);h.find('input[name="email"]').attr("value",n[1]);h.find('input[name="url"]').attr("value",n[2]);h.find('textarea[name="comment"]').text(k)}if(typeof jQuery!="undefined")jQuery.fn.paxPreFill=function(){this.each(function(){paxPreFill(jQuery(this))})};
function iso8601Seconds(h){h=new Date((h||"").replace(/-/g,"/").replace(/[TZ]/g," "));return h.getTime()-h.getTimezoneOffset()*6E4}
function prettyDate(h){var h=((new Date).getTime()-iso8601Seconds(h))/1E3,k=Math.floor(h/86400);if(!isNaN(k)&&!(k<0||k>=31))return k==0&&(h<60&&"Seconds ago"||h<120&&"1 minute ago"||h<3600&&Math.floor(h/60)+" minutes ago"||h<7200&&"1 hour ago"||h<86400&&Math.floor(h/3600)+" hours ago")||k==1&&"Yesterday"||k<7&&k+" days ago"||k<31&&Math.ceil(k/7)+" week"+(k>7?"s":"")+" ago"}
function paxNew(h){var k=iso8601Seconds(h.find("time").first().attr("datetime")),n=iso8601Seconds(getPaxCookie("visit"));k>n&&!isNaN(n)&&h.find("h1").first().prepend('<span class="new">\u2022</span>')}function paxNewComments(){var h=0;$("section.newest.comments article").each(function(){var k=$(this),n=iso8601Seconds(k.find("time").first().attr("datetime")),v=iso8601Seconds(getPaxCookie("visit"));n<v||isNaN(v)?k.remove():h=1});h==1&&$("section.newest.comments").css("display","block")}
if(typeof jQuery!="undefined")jQuery.fn.prettyDate=function(){return this.each(function(){var h=jQuery(this).children("time").last(),k=prettyDate(h.attr("datetime"));k&&h.find("a").text(k)})},jQuery.fn.paxNew=function(){paxNewComments();return this.each(function(){paxNew(jQuery(this))})};
jQuery.cookie=function(h,k,n){if(arguments.length>1&&String(k)!=="[object Object]"){n=jQuery.extend({},n);if(k===null||k===void 0)n.expires=-1;if(typeof n.expires==="number"){var v=n.expires,t=n.expires=new Date;t.setDate(t.getDate()+v)}k=String(k);return document.cookie=[encodeURIComponent(h),"=",n.raw?k:encodeURIComponent(k),n.expires?"; expires="+n.expires.toUTCString():"",n.path?"; path="+n.path:"",n.domain?"; domain="+n.domain:"",n.secure?"; secure":""].join("")}n=k||{};t=n.raw?function(h){return h}:
decodeURIComponent;return(v=RegExp("(?:^|; )"+h+"=([^;]*)").exec(document.cookie))?t(v[1]):null};function getPaxCookie(h){return $.cookie("pax_"+h,{raw:!1})}function getPaxUserCookie(){var h=[];h[0]=getPaxCookie("name");h[1]=getPaxCookie("email");h[2]=getPaxCookie("url");return h}var pInfScrLoading=!1,pInfScrIntraPageBackButton=0,pInfScrUrlCarryPageBase=null,pInfScrCount=[],pInfScrDelay=200;
function pInfScrExecute(){function h(h){return window.history&&history.pushState?(pInfScrUrlCarryPageBase==null&&(regexp=/\/pages?\/([0-9]+)-?[0-9]*\/?$/,regexp.test(window.location.href)?(nextPage=regexp.exec(window.location.href),pInfScrUrlCarryPageBase=nextPage[1]):(nextPage=regexp.exec(h),pInfScrUrlCarryPageBase=nextPage[1]-1)),h=h.replace("page/","pages/"+pInfScrUrlCarryPageBase+"-"),pInfScrIntraPageBackButton==1?window.history.pushState(null,null,h):window.history.replaceState(null,null,h),
!0):!1}$(document).height()-200<$(document).scrollTop()+$(window).height()&&pInfScrLoading==!1&&(pInfScrNode=$("article#more").last(),pInfScrURL=$("article#more p a").last().attr("href"),pInfScrNode.length>0&&pInfScrNode.css("display")!="none"&&h(pInfScrURL)&&$.ajax({type:"GET",url:pInfScrURL,beforeSend:function(){pInfScrLoading=!0;pInfScrNode.clone().empty().insertAfter(pInfScrNode).append('<img src="img/wait.gif" />');pInfScrNode.hide()},success:function(h){pInfScrNode.next().remove();h=$(h).filter("article").nodetype(1);
pInfScrCount.push(h.length);h.paxNew();h.prettyDate();h.insertBefore($("footer"));pInfScrLoading=!1},dataType:"html"}))}wait=new Image;wait.src="img/wait.gif";(function(h){var k={element:1,text:3,comment:8,document:9};h.fn.nodetype=function(h){h=typeof h==="string"?k[h.toLowerCase()]:h;return this.pushStack(this.filter(function(){return this.nodeType===h}),"nodetype",h)}})(jQuery);
function pvVote(h){var k=h.attr("href");$.ajax({type:"GET",url:k,success:function(k){h.replaceWith(k)},dataType:"text"})}var wantNewWindow=!1;
$(document).ready(function(){$("body").click(function(h){$(h.target).is("section.comments form button")?(h.preventDefault(),pcSave($(h.target))):$(h.target).is("span.vote a")?(h.preventDefault(),pvVote($(h.target))):$(h.target).is("a.discuss")&&wantNewWindow==!1&&h.button!=1&&(h.preventDefault(),pdLoad($(h.target)))});$(window).bind("keydown",function(h){if(h.which==224||h.which==91||h.which==93||h.which==17)wantNewWindow=!0});$(window).bind("keyup",function(h){if(h.which==224||h.which==91||h.which==
93||h.which==17)wantNewWindow=!1});$(window).scroll(function(){$.doTimeout("scroll",pInfScrDelay,pInfScrExecute);$(document).height()-200>$(document).scrollTop()+$(window).height()&&(pInfScrDelay=200)});$("article").prettyDate();window.onpopstate=function(){if(pInfScrIntraPageBackButton==1){if(pInfScrCount.length>0)var h=pInfScrCount.pop();for(i=1;i<=h;i++)$("body > article").last().remove();$("article#more").last().show();pInfScrDelay=3E3}};$("article").paxNew();$("article").paxPreFill()});

